from __future__ import annotations

from pathlib import Path

import nbformat as nbf


CELL_SPECS = [
    (
        "markdown",
        "# Stage 05 - Thesis Synthesis (Measure-Only)\n\n"
        "Route: `lst_models` V2\n"
        "Scope: `synthesis_measure_only`; official validation contact is "
        "`read_frozen_artifacts_only` (frozen Stage 03 / Stage 04 / V2.1 "
        "decision records are read and aggregated; zero new scoring events)\n"
        "User-facing notebook: `notebooks/05_thesis_synthesis_colab.ipynb`\n\n"
        "This notebook executes Stage 05 as pre-registered in "
        "`docs/protocols/05_thesis_synthesis_protocol.md`. Stage 05 is "
        "synthesis, not selection: it reads frozen upstream artifacts and "
        "packages the validation-budget ledger, claim boundary register, and "
        "expectation-calibration table. It performs no fit, no scoring, and no "
        "reselection; `no_final_model_selected=true` is carried into every "
        "output.\n",
    ),
    (
        "markdown",
        "## Frozen Protocol Summary\n\n"
        "- S5.1 validation-budget ledger: every official-validation / guarded "
        "scoring event across the route in one auditable table; each count is "
        "resolved from a frozen record field (Stage 03 "
        "`official_validation_scoring_events`, Stage 04 "
        "`new_validation_fit_predict_events`=0, V2.1 `guarded_scoring_events`), "
        "never hand-typed (Dwork 2015 reusable-holdout budget).\n"
        "- S5.2 claim boundary register: paper-safe statements tagged with one "
        "of three evidence domains (official_validation / train_inner_control / "
        "guarded_walkforward); the runner rejects any forbidden wording and any "
        "unknown domain.\n"
        "- S5.3 expectation calibration: the measured deltas situated against "
        "the published direction-classification context (~50% floor; low-to-mid "
        "50s% ceiling); measured values resolved from frozen records.\n"
        "- The V2.1 record describes a guarded historically-contacted contact "
        "that ALREADY happened; Stage 05 itself makes no new contact "
        "(`holdout_test_contact=false`, `new_scoring_events=0`). The heavier "
        "measure-only analyses this home unblocks (descriptive PBO/CSCV + "
        "`min_family_lcb`, AUGRC/MDE/abstention-by-activity, the four-estimand "
        "recompute + LOO) are recorded as `deferred_synthesis_items`.\n",
    ),
    (
        "markdown",
        "## Expected Artifacts\n\n"
        "When `RUN_STAGE05=True`, the runner writes:\n\n"
        "```text\n"
        "results/05_thesis_synthesis/<run_id>/\n"
        "  05_validation_budget_ledger.csv\n"
        "  05_claim_boundary_register.csv\n"
        "  05_expectation_calibration.csv\n"
        "  05_multiplicity_discount.csv\n"
        "  05_thesis_synthesis_report.json\n"
        "  run_manifest.json\n"
        "  artifact_inventory.csv\n"
        "```\n\n"
        "The durable-save cell uploads the run folder plus "
        "`drive_backup_manifest.json` to "
        "`My Drive/lst_models/results/05_thesis_synthesis/<run_id>/`.\n",
    ),
    (
        "code",
        "from pathlib import Path\n"
        "from datetime import datetime, timezone\n"
        "import importlib\n"
        "import json\n"
        "import subprocess\n"
        "import sys\n"
        "import zipfile\n\n"
        "RUN_PROJECT_BOOTSTRAP = True\n"
        "PROJECT_BOOTSTRAP_MODE = \"github_commit\"  # github_commit | manual_upload | already_present\n\n"
        "PROJECT_REPO_URL = \"https://github.com/zkc768/lstm-zhang.git\"\n"
        "PROJECT_REPO_COMMIT = \"50af24cf2fe916038249693a5c3b1aa426b759b8\"\n"
        "PROJECT_ROOT = Path(\"/content/lst_models\")\n\n"
        "RUN_STAGE03_DRIVE_SYNC = True\n"
        "RUN_STAGE04_DRIVE_SYNC = True\n"
        "RUN_V2_1_DRIVE_SYNC = True\n"
        "RUN_STAGE05_DRIVE_BACKUP = True\n"
        "RUN_STAGE05 = False\n"
        "RUN_ARTIFACT_DISPLAY = False\n\n"
        "STAGE_NAME = \"05_thesis_synthesis\"\n"
        "ROUTE = \"lst_models\"\n"
        "SCOPE = \"synthesis_measure_only\"\n"
        "HOLDOUT_TEST_CONTACT = False\n"
        "OFFICIAL_VALIDATION_CONTACT = \"read_frozen_artifacts_only\"\n"
        "NEW_SCORING_EVENTS = 0\n"
        "NO_FINAL_MODEL_SELECTED = True\n"
        "STAGE03_RUN_ID = \"20260610_133305_716174\"\n"
        "STAGE04_RUN_ID = \"20260618_234011_838683\"\n"
        "V2_1_RUN_ID = \"20260618_063559_889276\"\n"
        "STAGE03_OUTPUT_DIR = Path(\"/content/lst_models_results/03_frozen_validation_readout\") / STAGE03_RUN_ID\n"
        "STAGE04_OUTPUT_DIR = Path(\"/content/lst_models_results/04_diagnostics_ablation\") / STAGE04_RUN_ID\n"
        "V2_1_OUTPUT_DIR = Path(\"/content/lst_models_results/v2_1_guarded_walkforward_readout\") / V2_1_RUN_ID\n"
        "STAGE03_DRIVE_PATH_PARTS = [\"lst_models\", \"results\", \"03_frozen_validation_readout\", STAGE03_RUN_ID]\n"
        "STAGE04_DRIVE_PATH_PARTS = [\"lst_models\", \"results\", \"04_diagnostics_ablation\", STAGE04_RUN_ID]\n"
        "V2_1_DRIVE_PATH_PARTS = [\"lst_models\", \"results\", \"v2_1_guarded_walkforward_readout\", V2_1_RUN_ID]\n"
        "OUTPUT_DIR = Path(\"/content/lst_models_results/05_thesis_synthesis\")\n"
        "STAGE05_DRIVE_RESULT_PATH_PARTS = [\"lst_models\", \"results\", \"05_thesis_synthesis\"]\n\n"
        "def quote_drive_query_value(value):\n"
        "    return str(value).replace(\"\\\\\", \"\\\\\\\\\").replace(\"'\", \"\\\\'\")\n\n"
        "def run_cmd(args, cwd=None):\n"
        "    print(\"+\", \" \".join(str(arg) for arg in args))\n"
        "    subprocess.run(args, cwd=cwd, check=True)\n\n"
        "def looks_like_project_root(path):\n"
        "    return (\n"
        "        (path / \"configs\" / \"stages\" / \"05_thesis_synthesis.yaml\").exists()\n"
        "        and (path / \"docs\" / \"protocols\" / \"05_thesis_synthesis_protocol.md\").exists()\n"
        "        and (path / \"notebooks\" / \"05_thesis_synthesis_colab.ipynb\").exists()\n"
        "        and (path / \"src\" / \"lst_models\" / \"stages\" / \"thesis_synthesis.py\").exists()\n"
        "        and (path / \"src\" / \"lst_models\" / \"synthesis.py\").exists()\n"
        "    )\n\n"
        "def safe_extract_project_zip(zip_path):\n"
        "    destination = Path(\"/content\").resolve()\n"
        "    with zipfile.ZipFile(zip_path) as archive:\n"
        "        for member in archive.infolist():\n"
        "            member_path = Path(member.filename)\n"
        "            if member_path.is_absolute() or \"..\" in member_path.parts:\n"
        "                raise ValueError(f\"Unsafe path in uploaded zip: {member.filename}\")\n"
        "            target = (destination / member_path).resolve()\n"
        "            if target != destination and destination not in target.parents:\n"
        "                raise ValueError(f\"Unsafe path in uploaded zip: {member.filename}\")\n"
        "        archive.extractall(destination)\n"
        "    for candidate in [Path(\"/content/lst_models\"), Path(\"/content\") / zip_path.stem]:\n"
        "        if looks_like_project_root(candidate):\n"
        "            return candidate\n"
        "    raise FileNotFoundError(\"No lst_models project root found after zip extraction.\")\n\n"
        "def upload_and_extract_project_zip():\n"
        "    try:\n"
        "        from google.colab import files\n"
        "    except ImportError as exc:\n"
        "        raise RuntimeError(\"manual_upload mode only works inside Colab.\") from exc\n"
        "    uploaded = files.upload()\n"
        "    zip_names = [name for name in uploaded if name.endswith(\".zip\")]\n"
        "    if not zip_names:\n"
        "        raise ValueError(\"Upload a .zip file containing the lst_models project folder.\")\n"
        "    return safe_extract_project_zip(Path(\"/content\") / zip_names[0])\n\n"
        "if RUN_PROJECT_BOOTSTRAP:\n"
        "    if PROJECT_BOOTSTRAP_MODE == \"github_commit\":\n"
        "        if \"<\" in PROJECT_REPO_COMMIT:\n"
        "            raise ValueError(\"fill PROJECT_REPO_COMMIT with the Stage 05 full-bundle commit before bootstrapping\")\n"
        "        if (PROJECT_ROOT / \".git\").exists():\n"
        "            run_cmd([\"git\", \"fetch\", \"origin\"], cwd=PROJECT_ROOT)\n"
        "            run_cmd([\"git\", \"checkout\", PROJECT_REPO_COMMIT], cwd=PROJECT_ROOT)\n"
        "        else:\n"
        "            run_cmd([\"git\", \"clone\", PROJECT_REPO_URL, str(PROJECT_ROOT)])\n"
        "            run_cmd([\"git\", \"checkout\", PROJECT_REPO_COMMIT], cwd=PROJECT_ROOT)\n"
        "        actual_commit = subprocess.check_output([\"git\", \"rev-parse\", \"HEAD\"], cwd=PROJECT_ROOT, text=True).strip()\n"
        "        assert actual_commit == PROJECT_REPO_COMMIT, (actual_commit, PROJECT_REPO_COMMIT)\n"
        "    elif PROJECT_BOOTSTRAP_MODE == \"manual_upload\":\n"
        "        PROJECT_ROOT = upload_and_extract_project_zip()\n"
        "    elif PROJECT_BOOTSTRAP_MODE == \"already_present\":\n"
        "        pass\n"
        "    else:\n"
        "        raise ValueError(\"PROJECT_BOOTSTRAP_MODE must be github_commit, manual_upload, or already_present\")\n\n"
        "STAGE_CONFIG_PATH = PROJECT_ROOT / \"configs\" / \"stages\" / \"05_thesis_synthesis.yaml\"\n"
        "PROTOCOL_PATH = PROJECT_ROOT / \"docs\" / \"protocols\" / \"05_thesis_synthesis_protocol.md\"\n"
        "NOTEBOOK_PATH = PROJECT_ROOT / \"notebooks\" / \"05_thesis_synthesis_colab.ipynb\"\n"
        "STAGE_ENTRYPOINT_PATH = PROJECT_ROOT / \"src\" / \"lst_models\" / \"stages\" / \"thesis_synthesis.py\"\n"
        "SYNTHESIS_MODULE_PATH = PROJECT_ROOT / \"src\" / \"lst_models\" / \"synthesis.py\"\n"
        "REQUIRED_PROJECT_FILES = [STAGE_CONFIG_PATH, PROTOCOL_PATH, NOTEBOOK_PATH, STAGE_ENTRYPOINT_PATH, SYNTHESIS_MODULE_PATH]\n"
        "missing_project_files = [path for path in REQUIRED_PROJECT_FILES if not path.exists()]\n"
        "if missing_project_files:\n"
        "    missing_text = \"\\n\".join(f\"- {path}\" for path in missing_project_files)\n"
        "    raise FileNotFoundError(\"Stage 05 bootstrap target is missing required files:\\n\" + missing_text)\n\n"
        "SRC_PATH = PROJECT_ROOT / \"src\"\n"
        "if str(SRC_PATH) not in sys.path:\n"
        "    sys.path.insert(0, str(SRC_PATH))\n\n"
        "def clear_project_import_cache():\n"
        "    cached = [name for name in sys.modules if name == \"lst_models\" or name.startswith(\"lst_models.\")]\n"
        "    for name in cached:\n"
        "        del sys.modules[name]\n"
        "    importlib.invalidate_caches()\n\n"
        "clear_project_import_cache()\n\n"
        "print(\"PROJECT_ROOT:\", PROJECT_ROOT)\n"
        "print(\"PROJECT_BOOTSTRAP_MODE:\", PROJECT_BOOTSTRAP_MODE)\n"
        "print(\"PROJECT_COMMIT:\", PROJECT_REPO_COMMIT)\n"
        "print(\"STAGE03_RUN_ID:\", STAGE03_RUN_ID)\n"
        "print(\"STAGE04_RUN_ID:\", STAGE04_RUN_ID)\n"
        "print(\"V2_1_RUN_ID:\", V2_1_RUN_ID)\n"
        "print(\"OUTPUT_DIR:\", OUTPUT_DIR)\n"
        "print(\"RUN_STAGE05:\", RUN_STAGE05)\n"
        "print(\"RUN_STAGE05_DRIVE_BACKUP:\", RUN_STAGE05_DRIVE_BACKUP)\n",
    ),
    (
        "markdown",
        "## Config Load, Runtime Injection, And Contract Check\n\n"
        "This cell loads the Stage 05 config sidecar, injects the notebook "
        "runtime run-dir paths and exact upstream run ids BEFORE the contract "
        "asserts (runtime paths are part of the executable contract), and checks "
        "the measure-only flags. It does not read any decision record or "
        "aggregate anything.\n",
    ),
    (
        "code",
        "try:\n"
        "    import yaml\n"
        "except ModuleNotFoundError as exc:\n"
        "    raise ModuleNotFoundError(\"PyYAML is required to read the Stage 05 config.\") from exc\n\n"
        "def require_path(path):\n"
        "    if not path.exists():\n"
        "        raise FileNotFoundError(f\"missing required Stage 05 file: {path}\")\n\n"
        "require_path(STAGE_CONFIG_PATH)\n"
        "require_path(PROTOCOL_PATH)\n\n"
        "with STAGE_CONFIG_PATH.open(\"r\", encoding=\"utf-8\") as handle:\n"
        "    stage05_config = yaml.safe_load(handle)\n\n"
        "stage_inputs = stage05_config[\"inputs\"]\n"
        "stage_outputs = stage05_config[\"outputs\"]\n"
        "stage_inputs[\"stage03_run_id\"] = STAGE03_RUN_ID\n"
        "stage_inputs[\"stage03_runtime_run_dir\"] = str(STAGE03_OUTPUT_DIR)\n"
        "stage_inputs[\"stage03_drive_path_parts\"] = STAGE03_DRIVE_PATH_PARTS\n"
        "stage_inputs[\"stage04_run_id\"] = STAGE04_RUN_ID\n"
        "stage_inputs[\"stage04_runtime_run_dir\"] = str(STAGE04_OUTPUT_DIR)\n"
        "stage_inputs[\"stage04_drive_path_parts\"] = STAGE04_DRIVE_PATH_PARTS\n"
        "stage_inputs[\"v2_1_run_id\"] = V2_1_RUN_ID\n"
        "stage_inputs[\"v2_1_runtime_run_dir\"] = str(V2_1_OUTPUT_DIR)\n"
        "stage_inputs[\"v2_1_drive_path_parts\"] = V2_1_DRIVE_PATH_PARTS\n"
        "stage_outputs[\"output_dir\"] = str(OUTPUT_DIR)\n\n"
        "assert stage05_config[\"stage_name\"] == STAGE_NAME\n"
        "assert stage05_config[\"route\"] == ROUTE\n"
        "assert stage05_config[\"scope\"] == SCOPE\n"
        "assert stage05_config[\"holdout_test_contact\"] is HOLDOUT_TEST_CONTACT\n"
        "assert stage05_config[\"official_validation_contact\"] == OFFICIAL_VALIDATION_CONTACT\n"
        "assert int(stage05_config[\"new_scoring_events\"]) == NEW_SCORING_EVENTS\n"
        "assert stage05_config[\"no_final_model_selected\"] is NO_FINAL_MODEL_SELECTED\n"
        "assert stage05_config[\"official_validation_for_selection\"] is False\n"
        "assert stage_inputs[\"stage03_run_id\"] == STAGE03_RUN_ID\n"
        "assert stage_inputs[\"stage04_run_id\"] == STAGE04_RUN_ID\n"
        "assert stage_inputs[\"v2_1_run_id\"] == V2_1_RUN_ID\n"
        "assert Path(stage_outputs[\"output_dir\"]) == OUTPUT_DIR\n"
        "assert list(stage05_config[\"evidence_domains\"]) == [\"official_validation\", \"train_inner_control\", \"guarded_walkforward\"]\n"
        "assert stage05_config[\"forbidden\"][\"wording\"], \"forbidden wording list must be present\"\n"
        "expected_output_names = {\n"
        "    \"validation_budget_ledger\": \"05_validation_budget_ledger.csv\",\n"
        "    \"claim_boundary_register\": \"05_claim_boundary_register.csv\",\n"
        "    \"expectation_calibration\": \"05_expectation_calibration.csv\",\n"
        "    \"synthesis_report\": \"05_thesis_synthesis_report.json\",\n"
        "    \"manifest\": \"run_manifest.json\",\n"
        "    \"artifact_inventory\": \"artifact_inventory.csv\",\n"
        "}\n"
        "for output_key, output_name in expected_output_names.items():\n"
        "    assert stage_outputs[output_key] == output_name\n\n"
        "print(json.dumps({\n"
        "    \"stage_name\": stage05_config[\"stage_name\"],\n"
        "    \"source_stage03_run_id\": stage_inputs[\"stage03_run_id\"],\n"
        "    \"source_stage04_run_id\": stage_inputs[\"stage04_run_id\"],\n"
        "    \"source_v2_1_run_id\": stage_inputs[\"v2_1_run_id\"],\n"
        "    \"official_validation_contact\": stage05_config[\"official_validation_contact\"],\n"
        "    \"new_scoring_events\": stage05_config[\"new_scoring_events\"],\n"
        "    \"holdout_test_contact\": stage05_config[\"holdout_test_contact\"],\n"
        "}, indent=2))\n",
    ),
    (
        "markdown",
        "## Upstream Inputs: Stage 03 / Stage 04 / V2.1 Run Folders\n\n"
        "Stage 05 verifies the three frozen upstream run folders before "
        "anything runs. If the Colab runtime was restarted, this cell downloads "
        "the exact run folders by Drive path parts (duplicate Drive matches are "
        "a hard error). No raw data and no model weights are needed; Stage 05 "
        "reads only the decision records / report and the inventories.\n",
    ),
    (
        "code",
        "from lst_models.artifacts import require_artifacts\n\n"
        "def get_drive_service():\n"
        "    try:\n"
        "        from google.colab import auth\n"
        "        from googleapiclient.discovery import build\n"
        "    except ImportError as exc:\n"
        "        raise RuntimeError(\"Drive access only works inside Colab with Google API dependencies.\") from exc\n"
        "    auth.authenticate_user()\n"
        "    return build(\"drive\", \"v3\")\n\n"
        "def find_unique_drive_child(service, parent_id, name, mime_type=None):\n"
        "    escaped_name = quote_drive_query_value(name)\n"
        "    query_parts = [f\"name = '{escaped_name}'\", f\"'{parent_id}' in parents\", \"trashed = false\"]\n"
        "    if mime_type:\n"
        "        query_parts.append(f\"mimeType = '{mime_type}'\")\n"
        "    response = service.files().list(q=\" and \".join(query_parts), spaces=\"drive\", fields=\"files(id, name, mimeType, size)\", pageSize=10).execute()\n"
        "    matches = response.get(\"files\", [])\n"
        "    if len(matches) != 1:\n"
        "        raise FileNotFoundError(f\"expected exactly one Drive item named {name!r} under parent {parent_id}; found {len(matches)}\")\n"
        "    return matches[0]\n\n"
        "def resolve_drive_folder(service, path_parts):\n"
        "    folder_id = \"root\"\n"
        "    folder_mime = \"application/vnd.google-apps.folder\"\n"
        "    for folder_name in path_parts:\n"
        "        folder = find_unique_drive_child(service, folder_id, folder_name, folder_mime)\n"
        "        folder_id = folder[\"id\"]\n"
        "    return folder_id\n\n"
        "def download_drive_file(service, file_id, output_path):\n"
        "    from googleapiclient.http import MediaIoBaseDownload\n"
        "    output_path.parent.mkdir(parents=True, exist_ok=True)\n"
        "    request = service.files().get_media(fileId=file_id)\n"
        "    with output_path.open(\"wb\") as handle:\n"
        "        downloader = MediaIoBaseDownload(handle, request)\n"
        "        done = False\n"
        "        while not done:\n"
        "            _, done = downloader.next_chunk()\n\n"
        "def ensure_drive_folder(service, parent_id, name):\n"
        "    folder_mime = \"application/vnd.google-apps.folder\"\n"
        "    escaped_name = quote_drive_query_value(name)\n"
        "    query = f\"name = '{escaped_name}' and '{parent_id}' in parents and trashed = false and mimeType = '{folder_mime}'\"\n"
        "    matches = service.files().list(q=query, fields=\"files(id, name, webViewLink)\", pageSize=10).execute().get(\"files\", [])\n"
        "    if len(matches) == 1:\n"
        "        return matches[0][\"id\"]\n"
        "    if len(matches) > 1:\n"
        "        raise RuntimeError(f\"Duplicate Drive folders named {name!r} under parent {parent_id}\")\n"
        "    created = service.files().create(body={\"name\": name, \"mimeType\": folder_mime, \"parents\": [parent_id]}, fields=\"id, name, webViewLink\").execute()\n"
        "    return created[\"id\"]\n\n"
        "def ensure_drive_path(service, path_parts):\n"
        "    folder_id = \"root\"\n"
        "    for part in path_parts:\n"
        "        folder_id = ensure_drive_folder(service, folder_id, part)\n"
        "    return folder_id\n\n"
        "def find_drive_children(service, parent_id, name):\n"
        "    escaped_name = quote_drive_query_value(name)\n"
        "    query = f\"name = '{escaped_name}' and '{parent_id}' in parents and trashed = false\"\n"
        "    return service.files().list(q=query, fields=\"files(id, name, mimeType, size, webViewLink)\", pageSize=10).execute().get(\"files\", [])\n\n"
        "def upload_or_update_drive_file(service, parent_id, local_path, display_name=None):\n"
        "    from googleapiclient.http import MediaFileUpload\n"
        "    name = display_name or local_path.name\n"
        "    matches = find_drive_children(service, parent_id, name)\n"
        "    media = MediaFileUpload(str(local_path), resumable=True)\n"
        "    if len(matches) == 0:\n"
        "        uploaded = service.files().create(body={\"name\": name, \"parents\": [parent_id]}, media_body=media, fields=\"id, name, size, webViewLink\").execute()\n"
        "        action = \"uploaded\"\n"
        "    elif len(matches) == 1:\n"
        "        uploaded = service.files().update(fileId=matches[0][\"id\"], media_body=media, fields=\"id, name, size, webViewLink\").execute()\n"
        "        action = \"updated\"\n"
        "    else:\n"
        "        raise RuntimeError(f\"Duplicate Drive files named {name!r} under parent {parent_id}\")\n"
        "    print(f\"{action}: {name}\")\n"
        "    return dict(uploaded)\n\n"
        "def sync_stage_artifacts_from_drive(service, output_dir, path_parts, required_names, label):\n"
        "    run_folder_id = resolve_drive_folder(service, path_parts)\n"
        "    for artifact_name in required_names:\n"
        "        output_path = Path(output_dir) / artifact_name\n"
        "        if output_path.exists():\n"
        "            continue\n"
        "        file_meta = find_unique_drive_child(service, run_folder_id, artifact_name)\n"
        "        download_drive_file(service, file_meta[\"id\"], output_path)\n"
        "        print(f\"downloaded {label}: {artifact_name}\")\n\n"
        "required_stage03_artifacts = stage_inputs[\"required_stage03_artifacts\"]\n"
        "required_stage04_artifacts = stage_inputs[\"required_stage04_artifacts\"]\n"
        "required_v2_1_artifacts = stage_inputs[\"required_v2_1_artifacts\"]\n"
        "if RUN_STAGE05:\n"
        "    service = get_drive_service()\n"
        "    stage03_missing = [name for name in required_stage03_artifacts if not (STAGE03_OUTPUT_DIR / name).exists()]\n"
        "    if stage03_missing and RUN_STAGE03_DRIVE_SYNC:\n"
        "        sync_stage_artifacts_from_drive(service, STAGE03_OUTPUT_DIR, STAGE03_DRIVE_PATH_PARTS, stage03_missing, \"stage03\")\n"
        "    stage04_missing = [name for name in required_stage04_artifacts if not (STAGE04_OUTPUT_DIR / name).exists()]\n"
        "    if stage04_missing and RUN_STAGE04_DRIVE_SYNC:\n"
        "        sync_stage_artifacts_from_drive(service, STAGE04_OUTPUT_DIR, STAGE04_DRIVE_PATH_PARTS, stage04_missing, \"stage04\")\n"
        "    v2_1_missing = [name for name in required_v2_1_artifacts if not (V2_1_OUTPUT_DIR / name).exists()]\n"
        "    if v2_1_missing and RUN_V2_1_DRIVE_SYNC:\n"
        "        sync_stage_artifacts_from_drive(service, V2_1_OUTPUT_DIR, V2_1_DRIVE_PATH_PARTS, v2_1_missing, \"v2_1\")\n"
        "    require_artifacts(STAGE03_OUTPUT_DIR, required_stage03_artifacts)\n"
        "    require_artifacts(STAGE04_OUTPUT_DIR, required_stage04_artifacts)\n"
        "    require_artifacts(V2_1_OUTPUT_DIR, required_v2_1_artifacts)\n"
        "    print(\"Stage 03 / Stage 04 / V2.1 input checks passed.\")\n"
        "else:\n"
        "    print(\"RUN_STAGE05=False; upstream input sync skipped.\")\n",
    ),
    (
        "markdown",
        "## Run Stage 05 (Thesis Synthesis)\n\n"
        "The package-backed entry point is "
        "`lst_models.stages.thesis_synthesis.run_stage`. It reads the frozen "
        "decision records, resolves every synthesized number from a frozen "
        "field, and writes the four synthesis artifacts. No model is fit, "
        "predicted, scored, or selected. The committed notebook remains inert by "
        "default.\n",
    ),
    (
        "code",
        "if RUN_STAGE05:\n"
        "    try:\n"
        "        from lst_models.stages.thesis_synthesis import run_stage\n"
        "    except ModuleNotFoundError as exc:\n"
        "        raise ModuleNotFoundError(\"Missing Stage 05 package entry point: src/lst_models/stages/thesis_synthesis.py.\") from exc\n"
        "    result = run_stage(stage05_config)\n"
        "    display(result)\n"
        "    STAGE05_RUN_ID = Path(result.run_dir).name\n"
        "    if Path(result.run_dir).parent != OUTPUT_DIR:\n"
        "        raise RuntimeError(f\"Stage 05 output dir mismatch: {Path(result.run_dir).parent} != {OUTPUT_DIR}\")\n"
        "    print(\"STAGE05_RUN_ID:\", STAGE05_RUN_ID)\n"
        "else:\n"
        "    print(\"RUN_STAGE05=False; Stage 05 not executed.\")\n",
    ),
    (
        "markdown",
        "## Durable Drive Result Save\n\n"
        "Immediately after `run_stage` returns, this cell validates the seven "
        "required Stage 05 outputs (imported from the stage module, never "
        "retyped), refuses upload unless the run manifest records "
        "`new_scoring_events=0`, "
        "`official_validation_contact=read_frozen_artifacts_only`, "
        "`holdout_test_contact=false`, and `no_final_model_selected=true`, and "
        "uploads the run folder to "
        "`My Drive/lst_models/results/05_thesis_synthesis/<run_id>/`. "
        "`drive_backup_manifest.json` is written and uploaded last; its own "
        "entry records size null (self-reference).\n",
    ),
    (
        "code",
        "from lst_models.stages.thesis_synthesis import REQUIRED_STAGE05_ARTIFACTS\n\n"
        "def backup_stage05_results_to_drive(output_run_dir):\n"
        "    run_dir = Path(output_run_dir)\n"
        "    if not run_dir.exists():\n"
        "        raise FileNotFoundError(f\"Stage 05 output folder not found: {run_dir}\")\n"
        "    run_id = run_dir.name\n"
        "    missing = [name for name in REQUIRED_STAGE05_ARTIFACTS if not (run_dir / name).exists()]\n"
        "    if missing:\n"
        "        raise FileNotFoundError(\n"
        "            \"Missing required Stage 05 artifacts before Drive backup in \"\n"
        "            f\"{run_dir}: {missing}\"\n"
        "        )\n"
        "    run_manifest = json.loads((run_dir / \"run_manifest.json\").read_text(encoding=\"utf-8\"))\n"
        "    if int(run_manifest.get(\"new_scoring_events\", -1)) != 0:\n"
        "        raise ValueError(\"Stage 05 backup refused: run manifest must record new_scoring_events=0\")\n"
        "    if run_manifest.get(\"official_validation_contact\") != \"read_frozen_artifacts_only\":\n"
        "        raise ValueError(\"Stage 05 backup refused: run manifest must record official_validation_contact=read_frozen_artifacts_only\")\n"
        "    if run_manifest.get(\"holdout_test_contact\") is not False:\n"
        "        raise ValueError(\"Stage 05 backup refused: run manifest must record holdout_test_contact=false\")\n"
        "    if run_manifest.get(\"no_final_model_selected\") is not True:\n"
        "        raise ValueError(\"Stage 05 backup refused: run manifest must record no_final_model_selected=true\")\n"
        "    if run_manifest.get(\"source_stage03_run_id\") != STAGE03_RUN_ID:\n"
        "        raise ValueError(f\"Stage 05 backup refused: manifest source_stage03_run_id != {STAGE03_RUN_ID}\")\n"
        "    if run_manifest.get(\"source_stage04_run_id\") != STAGE04_RUN_ID:\n"
        "        raise ValueError(f\"Stage 05 backup refused: manifest source_stage04_run_id != {STAGE04_RUN_ID}\")\n"
        "    if run_manifest.get(\"source_v2_1_run_id\") != V2_1_RUN_ID:\n"
        "        raise ValueError(f\"Stage 05 backup refused: manifest source_v2_1_run_id != {V2_1_RUN_ID}\")\n"
        "    service = get_drive_service()\n"
        "    drive_path_parts = STAGE05_DRIVE_RESULT_PATH_PARTS + [run_id]\n"
        "    drive_folder_id = ensure_drive_path(service, drive_path_parts)\n"
        "    backup_manifest_path = run_dir / \"drive_backup_manifest.json\"\n"
        "    local_files = sorted(path for path in run_dir.rglob(\"*\") if path.is_file() and path.name != backup_manifest_path.name)\n"
        "    uploads = []\n"
        "    for path in local_files:\n"
        "        uploaded = upload_or_update_drive_file(service, drive_folder_id, path)\n"
        "        uploaded[\"bytes\"] = path.stat().st_size\n"
        "        uploads.append(uploaded)\n"
        "    backup_manifest = {\n"
        "        \"stage_name\": STAGE_NAME,\n"
        "        \"run_id\": run_id,\n"
        "        \"stage_run_id\": run_id,\n"
        "        \"new_scoring_events\": run_manifest.get(\"new_scoring_events\"),\n"
        "        \"local_output_dir\": str(run_dir),\n"
        "        \"drive_path\": \"My Drive/\" + \"/\".join(drive_path_parts),\n"
        "        \"drive_path_parts\": drive_path_parts,\n"
        "        \"drive_folder_id\": drive_folder_id,\n"
        "        \"uploaded_file_names\": [upload[\"name\"] for upload in uploads],\n"
        "        \"uploaded_files\": uploads,\n"
        "        \"sync_timestamp_utc\": datetime.now(timezone.utc).isoformat(),\n"
        "        \"holdout_test_contact\": run_manifest.get(\"holdout_test_contact\"),\n"
        "        \"official_validation_contact\": run_manifest.get(\"official_validation_contact\"),\n"
        "        \"no_final_model_selected\": run_manifest.get(\"no_final_model_selected\"),\n"
        "    }\n"
        "    backup_manifest[\"uploaded_files\"] = backup_manifest[\"uploaded_files\"] + [\n"
        "        {\"name\": backup_manifest_path.name, \"bytes\": None, \"self_reference\": True}\n"
        "    ]\n"
        "    backup_manifest[\"uploaded_file_names\"].append(backup_manifest_path.name)\n"
        "    backup_manifest_path.write_text(json.dumps(backup_manifest, indent=2), encoding=\"utf-8\")\n"
        "    upload_or_update_drive_file(service, drive_folder_id, backup_manifest_path)\n"
        "    print(\"stage_run_id:\", backup_manifest[\"stage_run_id\"])\n"
        "    print(\"drive_path:\", backup_manifest[\"drive_path\"])\n"
        "    print(\"drive_folder_id:\", backup_manifest[\"drive_folder_id\"])\n"
        "    return backup_manifest\n\n"
        "if RUN_STAGE05_DRIVE_BACKUP and RUN_STAGE05:\n"
        "    if \"result\" not in globals():\n"
        "        raise RuntimeError(\"RUN_STAGE05_DRIVE_BACKUP=True requires running Stage 05 first.\")\n"
        "    stage05_drive_backup_manifest = backup_stage05_results_to_drive(result.run_dir)\n"
        "else:\n"
        "    print(\"RUN_STAGE05_DRIVE_BACKUP is disabled or RUN_STAGE05=False; no Stage 05 result backup uploaded.\")\n",
    ),
    (
        "markdown",
        "## Synthesis Display\n\n"
        "After a run, display only Stage 05 artifacts from `result.run_dir`: the "
        "validation-budget ledger, the claim boundary register, the "
        "expectation-calibration table, and the synthesis report summary. "
        "Nothing here marks, recommends, or selects an operating point or a "
        "model.\n",
    ),
    (
        "code",
        "if RUN_ARTIFACT_DISPLAY:\n"
        "    import pandas as pd\n\n"
        "    if \"result\" not in globals():\n"
        "        raise RuntimeError(\"RUN_ARTIFACT_DISPLAY=True requires running Stage 05 first.\")\n"
        "    run_dir = Path(result.run_dir)\n"
        "    report = json.loads((run_dir / \"05_thesis_synthesis_report.json\").read_text(encoding=\"utf-8\"))\n"
        "    print(json.dumps({\n"
        "        \"stage03_decision\": report.get(\"stage03_decision\"),\n"
        "        \"v2_1_decision\": report.get(\"v2_1_decision\"),\n"
        "        \"scoring_event_budget\": report.get(\"scoring_event_budget\"),\n"
        "        \"v2_1_pooled_delta_estimands\": report.get(\"v2_1_pooled_delta_estimands\"),\n"
        "        \"multiplicity_discount\": report.get(\"multiplicity_discount\"),\n"
        "        \"claim_count\": report.get(\"claim_count\"),\n"
        "        \"limitation_count\": report.get(\"limitation_count\"),\n"
        "        \"deferred_synthesis_items\": report.get(\"deferred_synthesis_items\"),\n"
        "    }, indent=2))\n"
        "    display(pd.read_csv(run_dir / \"05_validation_budget_ledger.csv\"))\n"
        "    display(pd.read_csv(run_dir / \"05_claim_boundary_register.csv\"))\n"
        "    display(pd.read_csv(run_dir / \"05_expectation_calibration.csv\"))\n"
        "    display(pd.read_csv(run_dir / \"05_multiplicity_discount.csv\"))\n"
        "else:\n"
        "    print(\"RUN_ARTIFACT_DISPLAY=False; no Stage 05 artifacts displayed.\")\n",
    ),
    (
        "markdown",
        "## Honest Interpretation Template\n\n"
        "Stage 05 is synthesis, not selection. It reads frozen artifacts and "
        "aggregates them measure-only; `no_final_model_selected=true` is carried "
        "into every output.\n\n"
        "Do not claim a final model, an official validation winner, a holdout "
        "winner, a test winner, proven generalization, profitability, "
        "tradeability, or a chosen threshold from this notebook. The guarded "
        "walk-forward evidence is guarded historically-contacted, not an "
        "unseen-data result.\n\n"
        "Required context sentences for any summary based on this run:\n\n"
        "- The validation-budget ledger aggregates every official-validation and "
        "guarded scoring event across the route; each count is resolved from a "
        "frozen record field, never hand-typed.\n"
        "- Every claim names exactly one of three evidence domains and is never "
        "mixed across domains in a single quantitative comparison.\n"
        "- The low-activity (calm-bar) edge is a conditional-signal limitation, "
        "not an innovation; 'activity' is a per-day eligible-row-count proxy, not "
        "realized volume or liquidity.\n"
        "- A small macro-F1 delta is not evidence of tradeability; no economic "
        "analysis is performed or claimed.\n"
        "- The heavier measure-only analyses (descriptive PBO/CSCV, AUGRC/MDE, "
        "the four-estimand recompute) are listed as `deferred_synthesis_items` "
        "and are not yet computed in this bundle.\n",
    ),
]


def build_notebook() -> nbf.NotebookNode:
    nb = nbf.v4.new_notebook()
    nb.metadata = {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "pygments_lexer": "ipython3"},
        "colab": {"provenance": []},
    }
    nb.cells = []
    for cell_type, cell_source in CELL_SPECS:
        if cell_type == "markdown":
            cell = nbf.v4.new_markdown_cell(cell_source)
        elif cell_type == "code":
            cell = nbf.v4.new_code_cell(cell_source)
            cell.outputs = []
            cell.execution_count = None
        else:
            raise ValueError(f"unsupported cell type: {cell_type}")
        cell.metadata = {}
        nb.cells.append(cell)
    return nb


def main() -> None:
    root = Path(__file__).resolve().parents[2]
    output_path = root / "notebooks" / "05_thesis_synthesis_colab.ipynb"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(build_notebook(), output_path)
    print(output_path)


if __name__ == "__main__":
    main()
