from __future__ import annotations

from pathlib import Path

import nbformat as nbf


CELL_SPECS = [
    (
        "markdown",
        "# Stage 02 - Model HPO Train-Inner\n\n"
        "Route: `lst_models` V2\n"
        "Scope: `validation_only`\n"
        "User-facing notebook: `notebooks/02_model_hpo_train_inner_colab.ipynb`\n\n"
        "This notebook runs the Stage 02 package entry point against the exact "
        "Stage 00 and Stage 01 handoffs. Stage 02 is formal train-inner HPO "
        "only. It does not read official validation, test, or holdout rows and "
        "does not determine the final model.\n",
    ),
    (
        "markdown",
        "## Protocol Summary\n\n"
        "Stage 02 consumes the frozen Stage 00 split/label/sample artifacts and "
        "`01_candidate_inputs.json` from one frozen Stage 01 run folder. It "
        "executes bounded, predeclared HPO profiles for every Stage "
        "01-approved core family enabled in the config:\n\n"
        "- `lightgbm`\n"
        "- `standard_dlinear`\n"
        "- `tcn`\n"
        "- `ms_dlinear_tcn`\n\n"
        "All comparisons are made on train-inner folds only, with same-row "
        "baseline controls. `simple_gru` and `shallow_lstm` remain optional "
        "fixed controls, not formal HPO families.\n",
    ),
    (
        "markdown",
        "## Expected Artifacts\n\n"
        "When `RUN_STAGE02=True`, Stage 02 writes:\n\n"
        "```text\n"
        "results/02_model_hpo_train_inner/<run_id>/\n"
        "  run_manifest.json\n"
        "  artifact_inventory.csv\n"
        "  02_model_hpo_train_inner_summary.csv\n"
        "  02_hpo_plan_ledger.csv\n"
        "  02_hpo_trial_ledger.csv\n"
        "  02_hpo_summary.csv\n"
        "  02_baseline_control_summary.csv\n"
        "  02_frozen_candidate.json\n"
        "  02_frozen_candidate.md\n"
        "  02_best_params_by_family.json\n"
        "  02_stage03_handoff.json\n"
        "  frozen_params/*.yaml  # only when primary/fallback freeze succeeds\n"
        "```\n\n"
        "`02_stage03_handoff.json` is the only readiness gate for Stage 03. "
        "Stage 03 must not start if `ready_for_stage03=false`.\n",
    ),
    (
        "code",
        "from pathlib import Path\n"
        "from datetime import datetime, timezone\n"
        "import importlib\n"
        "import json\n"
        "import shutil\n"
        "import subprocess\n"
        "import sys\n"
        "import zipfile\n\n"
        "RUN_PROJECT_BOOTSTRAP = True\n"
        "PROJECT_BOOTSTRAP_MODE = \"github_commit\"  # github_commit | manual_upload | already_present\n\n"
        "PROJECT_REPO_URL = \"https://github.com/zkc768/lstm-zhang.git\"\n"
        "PROJECT_REPO_COMMIT = \"4672f4d27e3e8a009ce95bc5344cadc0aac398e1\"\n"
        "PROJECT_ROOT = Path(\"/content/lst_models\")\n\n"
        "RUN_STAGE00_DRIVE_SYNC = True\n"
        "RUN_STAGE01_DRIVE_SYNC = True\n"
        "RUN_RAW_DATA_SYNC = True\n"
        "RUN_STAGE02_CHECKPOINT = False\n"
        "RUN_STAGE02_DRIVE_BACKUP = True\n"
        "RUN_STAGE02 = False\n"
        "RUN_ARTIFACT_DISPLAY = False\n\n"
        "STAGE_NAME = \"02_model_hpo_train_inner\"\n"
        "ROUTE = \"lst_models\"\n"
        "SCOPE = \"validation_only\"\n"
        "HOLDOUT_TEST_CONTACT = False\n"
        "STAGE00_RUN_ID = \"20260610_051705_347450\"\n"
        "STAGE01_RUN_ID = \"20260610_075002\"\n"
        "SUPERSEDED_STAGE02_RUN_IDS = [\"20260609_100637_704705\"]\n"
        "STAGE02_RUN_ID = datetime.now(timezone.utc).strftime(\"%Y%m%d_%H%M%S_%f\")\n"
        "STAGE00_OUTPUT_DIR = Path(\"/content/lst_models_results/00_data_split_label_freeze\") / STAGE00_RUN_ID\n"
        "STAGE01_OUTPUT_DIR = Path(\"/content/lst_models_results/01_feature_window_search\") / STAGE01_RUN_ID\n"
        "STAGE02_OUTPUT_DIR = Path(\"/content/lst_models_results/02_model_hpo_train_inner\") / STAGE02_RUN_ID\n"
        "STAGE00_DRIVE_PATH_PARTS = [\"lst_models\", \"results\", \"00_data_split_label_freeze\", STAGE00_RUN_ID]\n"
        "STAGE01_DRIVE_PATH_PARTS = [\"lst_models\", \"results\", \"01_feature_window_search\", STAGE01_RUN_ID]\n"
        "OUTPUT_DIR = Path(\"/content/lst_models_results/02_model_hpo_train_inner\")\n"
        "STAGE02_DRIVE_RESULT_PATH_PARTS = [\"lst_models\", \"results\", \"02_model_hpo_train_inner\"]\n"
        "RAW_DATA_DIR = Path(\"/content/lst_models_raw_stock_data\")\n"
        "CHECKPOINT_ROOT = Path(\"/content/lst_models_checkpoints/02_model_hpo_train_inner\")\n"
        "CHECKPOINT_DRIVE_PATH_PARTS = [\"lst_models\", \"checkpoints\", \"02_model_hpo_train_inner\", STAGE02_RUN_ID]\n"
        "CORE_HPO_FAMILIES = [\"lightgbm\", \"standard_dlinear\", \"tcn\", \"ms_dlinear_tcn\"]\n"
        "BASELINE_REGISTRY_NAMES = [\"stratified_dummy_train_prior\", \"majority_train_prior\", \"constant_up\", \"constant_down\"]\n\n"
        "def quote_drive_query_value(value):\n"
        "    return str(value).replace(\"\\\\\", \"\\\\\\\\\").replace(\"'\", \"\\\\'\")\n\n"
        "def run_cmd(args, cwd=None):\n"
        "    print(\"+\", \" \".join(str(arg) for arg in args))\n"
        "    subprocess.run(args, cwd=cwd, check=True)\n\n"
        "def looks_like_project_root(path):\n"
        "    return (\n"
        "        (path / \"configs\" / \"stages\" / \"02_model_hpo_train_inner.yaml\").exists()\n"
        "        and (path / \"docs\" / \"protocols\" / \"02_model_hpo_train_inner_protocol.md\").exists()\n"
        "        and (path / \"notebooks\" / \"02_model_hpo_train_inner_colab.ipynb\").exists()\n"
        "        and (path / \"src\" / \"lst_models\" / \"stages\" / \"model_hpo_train_inner.py\").exists()\n"
        "    )\n\n"
        "def safe_extract_project_zip(zip_path):\n"
        "    destination = Path(\"/content\").resolve()\n"
        "    with zipfile.ZipFile(zip_path) as archive:\n"
        "        for member in archive.infolist():\n"
        "            member_path = Path(member.filename)\n"
        "            if member_path.is_absolute() or \"..\" in member_path.parts:\n"
        "                raise ValueError(f\"Unsafe path in uploaded zip: {member.filename}\")\n"
        "            target = (destination / member_path).resolve()\n"
        "            if target != destination and destination not in target.parents:\n"
        "                raise ValueError(f\"Unsafe path in uploaded zip: {member.filename}\")\n"
        "        archive.extractall(destination)\n"
        "    for candidate in [Path(\"/content/lst_models\"), Path(\"/content\") / zip_path.stem]:\n"
        "        if looks_like_project_root(candidate):\n"
        "            return candidate\n"
        "    raise FileNotFoundError(\"No lst_models project root found after zip extraction.\")\n\n"
        "def upload_and_extract_project_zip():\n"
        "    try:\n"
        "        from google.colab import files\n"
        "    except ImportError as exc:\n"
        "        raise RuntimeError(\"manual_upload mode only works inside Colab.\") from exc\n"
        "    uploaded = files.upload()\n"
        "    zip_names = [name for name in uploaded if name.endswith(\".zip\")]\n"
        "    if not zip_names:\n"
        "        raise ValueError(\"Upload a .zip file containing the lst_models project folder.\")\n"
        "    return safe_extract_project_zip(Path(\"/content\") / zip_names[0])\n\n"
        "if RUN_PROJECT_BOOTSTRAP:\n"
        "    if PROJECT_BOOTSTRAP_MODE == \"github_commit\":\n"
        "        if (PROJECT_ROOT / \".git\").exists():\n"
        "            run_cmd([\"git\", \"fetch\", \"origin\"], cwd=PROJECT_ROOT)\n"
        "            run_cmd([\"git\", \"checkout\", PROJECT_REPO_COMMIT], cwd=PROJECT_ROOT)\n"
        "        else:\n"
        "            run_cmd([\"git\", \"clone\", PROJECT_REPO_URL, str(PROJECT_ROOT)])\n"
        "            run_cmd([\"git\", \"checkout\", PROJECT_REPO_COMMIT], cwd=PROJECT_ROOT)\n"
        "        actual_commit = subprocess.check_output([\"git\", \"rev-parse\", \"HEAD\"], cwd=PROJECT_ROOT, text=True).strip()\n"
        "        assert actual_commit == PROJECT_REPO_COMMIT, (actual_commit, PROJECT_REPO_COMMIT)\n"
        "    elif PROJECT_BOOTSTRAP_MODE == \"manual_upload\":\n"
        "        PROJECT_ROOT = upload_and_extract_project_zip()\n"
        "    elif PROJECT_BOOTSTRAP_MODE == \"already_present\":\n"
        "        pass\n"
        "    else:\n"
        "        raise ValueError(\"PROJECT_BOOTSTRAP_MODE must be github_commit, manual_upload, or already_present\")\n\n"
        "STAGE_CONFIG_PATH = PROJECT_ROOT / \"configs\" / \"stages\" / \"02_model_hpo_train_inner.yaml\"\n"
        "PROTOCOL_PATH = PROJECT_ROOT / \"docs\" / \"protocols\" / \"02_model_hpo_train_inner_protocol.md\"\n"
        "NOTEBOOK_PATH = PROJECT_ROOT / \"notebooks\" / \"02_model_hpo_train_inner_colab.ipynb\"\n"
        "STAGE_ENTRYPOINT_PATH = PROJECT_ROOT / \"src\" / \"lst_models\" / \"stages\" / \"model_hpo_train_inner.py\"\n"
        "RAW_DATA_MANIFEST_PATH = PROJECT_ROOT / \"configs\" / \"lst_models_data.yaml\"\n"
        "SEARCH_SPACE_PATHS = [PROJECT_ROOT / \"configs\" / \"models\" / family / \"search_space.yaml\" for family in CORE_HPO_FAMILIES]\n"
        "REQUIRED_PROJECT_FILES = [STAGE_CONFIG_PATH, PROTOCOL_PATH, NOTEBOOK_PATH, STAGE_ENTRYPOINT_PATH, RAW_DATA_MANIFEST_PATH, *SEARCH_SPACE_PATHS]\n"
        "missing_project_files = [path for path in REQUIRED_PROJECT_FILES if not path.exists()]\n"
        "if missing_project_files:\n"
        "    missing_text = \"\\n\".join(f\"- {path}\" for path in missing_project_files)\n"
        "    raise FileNotFoundError(\"Stage 02 bootstrap target is missing required files:\\n\" + missing_text)\n\n"
        "SRC_PATH = PROJECT_ROOT / \"src\"\n"
        "if str(SRC_PATH) not in sys.path:\n"
        "    sys.path.insert(0, str(SRC_PATH))\n\n"
        "def clear_project_import_cache():\n"
        "    cached = [name for name in sys.modules if name == \"lst_models\" or name.startswith(\"lst_models.\")]\n"
        "    for name in cached:\n"
        "        del sys.modules[name]\n"
        "    importlib.invalidate_caches()\n\n"
        "clear_project_import_cache()\n\n"
        "print(\"PROJECT_ROOT:\", PROJECT_ROOT)\n"
        "print(\"PROJECT_BOOTSTRAP_MODE:\", PROJECT_BOOTSTRAP_MODE)\n"
        "print(\"PROJECT_REPO_URL:\", PROJECT_REPO_URL)\n"
        "print(\"PROJECT_COMMIT:\", PROJECT_REPO_COMMIT)\n"
        "print(\"STAGE00_RUN_ID:\", STAGE00_RUN_ID)\n"
        "print(\"STAGE01_RUN_ID:\", STAGE01_RUN_ID)\n"
        "print(\"STAGE02_RUN_ID:\", STAGE02_RUN_ID)\n"
        "print(\"SUPERSEDED_STAGE02_RUN_IDS:\", SUPERSEDED_STAGE02_RUN_IDS)\n"
        "print(\"STAGE00_OUTPUT_DIR:\", STAGE00_OUTPUT_DIR)\n"
        "print(\"STAGE01_OUTPUT_DIR:\", STAGE01_OUTPUT_DIR)\n"
        "print(\"STAGE02_OUTPUT_DIR:\", STAGE02_OUTPUT_DIR)\n"
        "print(\"RAW_DATA_DIR:\", RAW_DATA_DIR)\n"
        "print(\"OUTPUT_DIR:\", OUTPUT_DIR)\n"
        "print(\"STAGE02_DRIVE_RESULT_PATH_PARTS:\", STAGE02_DRIVE_RESULT_PATH_PARTS)\n"
        "print(\"CHECKPOINT_ROOT:\", CHECKPOINT_ROOT)\n"
        "print(\"CHECKPOINT_DRIVE_PATH_PARTS:\", CHECKPOINT_DRIVE_PATH_PARTS)\n"
        "print(\"RUN_STAGE00_DRIVE_SYNC:\", RUN_STAGE00_DRIVE_SYNC)\n"
        "print(\"RUN_STAGE01_DRIVE_SYNC:\", RUN_STAGE01_DRIVE_SYNC)\n"
        "print(\"RUN_RAW_DATA_SYNC:\", RUN_RAW_DATA_SYNC)\n"
        "print(\"RUN_STAGE02_CHECKPOINT:\", RUN_STAGE02_CHECKPOINT)\n"
        "print(\"RUN_STAGE02_DRIVE_BACKUP:\", RUN_STAGE02_DRIVE_BACKUP)\n"
        "print(\"RUN_STAGE02:\", RUN_STAGE02)\n"
        "print(\"RUN_ARTIFACT_DISPLAY:\", RUN_ARTIFACT_DISPLAY)\n",
    ),
    (
        "markdown",
        "## Config Load And Contract Check\n\n"
        "This cell reads the Stage 02 config sidecar and checks the notebook-facing "
        "contract. It does not fit models or read official validation metrics.\n",
    ),
    (
        "code",
        "try:\n"
        "    import yaml\n"
        "except ModuleNotFoundError as exc:\n"
        "    raise ModuleNotFoundError(\"PyYAML is required to read the Stage 02 config.\") from exc\n\n"
        "def require_path(path):\n"
        "    if not path.exists():\n"
        "        raise FileNotFoundError(f\"missing required Stage 02 file: {path}\")\n\n"
        "require_path(STAGE_CONFIG_PATH)\n"
        "require_path(PROTOCOL_PATH)\n"
        "require_path(RAW_DATA_MANIFEST_PATH)\n\n"
        "with STAGE_CONFIG_PATH.open(\"r\", encoding=\"utf-8\") as handle:\n"
        "    stage02_config = yaml.safe_load(handle)\n\n"
        "stage_inputs = stage02_config[\"inputs\"]\n"
        "stage_outputs = stage02_config[\"outputs\"]\n"
        "stage_checkpointing = stage02_config[\"checkpointing\"]\n"
        "stage02_config[\"superseded_stage02_run_ids\"] = SUPERSEDED_STAGE02_RUN_IDS\n"
        "stage_inputs[\"stage00_run_id\"] = STAGE00_RUN_ID\n"
        "stage_inputs[\"stage00_runtime_run_dir\"] = str(STAGE00_OUTPUT_DIR)\n"
        "stage_inputs[\"stage00_drive_path_parts\"] = STAGE00_DRIVE_PATH_PARTS\n"
        "stage_inputs[\"stage00_run_manifest\"] = str(STAGE00_OUTPUT_DIR / \"run_manifest.json\")\n"
        "stage_inputs[\"stage01_run_id\"] = STAGE01_RUN_ID\n"
        "stage_inputs[\"stage01_runtime_run_dir\"] = str(STAGE01_OUTPUT_DIR)\n"
        "stage_inputs[\"stage01_drive_path_parts\"] = STAGE01_DRIVE_PATH_PARTS\n"
        "stage_inputs[\"stage01_candidate_inputs\"] = str(STAGE01_OUTPUT_DIR / \"01_candidate_inputs.json\")\n"
        "stage_inputs[\"raw_data_dir\"] = str(RAW_DATA_DIR)\n"
        "stage_outputs[\"output_dir\"] = str(OUTPUT_DIR)\n"
        "stage_outputs[\"run_id\"] = STAGE02_RUN_ID\n"
        "stage_checkpointing[\"checkpoint_dir\"] = str(CHECKPOINT_ROOT)\n"
        "assert stage02_config[\"stage_name\"] == STAGE_NAME\n"
        "assert stage02_config[\"route\"] == ROUTE\n"
        "assert stage02_config[\"scope\"] == SCOPE\n"
        "assert stage02_config[\"holdout_test_contact\"] is HOLDOUT_TEST_CONTACT\n"
        "assert stage02_config[\"superseded_stage02_run_ids\"] == SUPERSEDED_STAGE02_RUN_IDS\n"
        "assert stage_inputs[\"stage00_run_id\"] == STAGE00_RUN_ID\n"
        "assert Path(stage_inputs[\"stage00_runtime_run_dir\"]) == STAGE00_OUTPUT_DIR\n"
        "assert stage_inputs[\"stage00_drive_path_parts\"] == STAGE00_DRIVE_PATH_PARTS\n"
        "assert stage_inputs[\"stage01_run_id\"] == STAGE01_RUN_ID\n"
        "assert Path(stage_inputs[\"stage01_runtime_run_dir\"]) == STAGE01_OUTPUT_DIR\n"
        "assert stage_inputs[\"stage01_drive_path_parts\"] == STAGE01_DRIVE_PATH_PARTS\n"
        "assert Path(stage_inputs[\"raw_data_dir\"]) == RAW_DATA_DIR\n"
        "assert Path(stage_outputs[\"output_dir\"]) == OUTPUT_DIR\n"
        "assert stage_outputs[\"run_id\"] == STAGE02_RUN_ID\n"
        "assert Path(stage_checkpointing[\"checkpoint_dir\"]) == CHECKPOINT_ROOT\n"
        "assert stage_inputs[\"raw_data_manifest\"] == \"configs/lst_models_data.yaml\"\n"
        "assert [family for family, spec in stage02_config[\"hpo_families\"].items() if spec[\"enabled\"]] == CORE_HPO_FAMILIES\n"
        "assert stage02_config[\"baseline_controls\"][\"mandatory\"] == BASELINE_REGISTRY_NAMES\n"
        "assert stage02_config[\"lightgbm_training_defaults\"][\"early_stopping_validation_source\"] == \"inner_train_chronological_tail\"\n"
        "torch_defaults = stage02_config[\"probe_training_defaults\"][\"torch\"]\n"
        "assert torch_defaults[\"early_stopping\"] == \"inner_train_chronological_tail\"\n"
        "assert torch_defaults[\"early_stopping_patience\"] >= 1\n"
        "assert torch_defaults[\"gradient_clip_norm\"] > 0\n"
        "assert stage02_config[\"selection_rules\"][\"minimum_positive_ticker_count\"] >= 1\n"
        "assert stage02_config[\"selection_rules\"][\"max_selected_configs_per_family\"] == 1\n"
        "assert stage02_config[\"selection_rules\"][\"no_official_validation_selection\"] is True\n"
        "assert stage02_config[\"selection_rules\"][\"no_final_model_selected\"] is True\n"
        "for required_output in [\"hpo_trial_ledger\", \"hpo_summary\", \"baseline_control_summary\", \"frozen_candidate\", \"frozen_candidate_markdown\"]:\n"
        "    assert required_output in stage_outputs\n\n"
        "profile_counts = {}\n"
        "for family in CORE_HPO_FAMILIES:\n"
        "    search_space_path = PROJECT_ROOT / stage02_config[\"hpo_families\"][family][\"search_space\"]\n"
        "    require_path(search_space_path)\n"
        "    with search_space_path.open(\"r\", encoding=\"utf-8\") as handle:\n"
        "        search_space = yaml.safe_load(handle)\n"
        "    profile_counts[family] = len(search_space.get(\"profiles\", []))\n"
        "per_candidate_input_plan_rows = sum(profile_counts.values()) * int(stage02_config[\"train_inner\"][\"n_folds\"]) * len(stage02_config[\"train_inner\"][\"seeds\"])\n"
        "max_candidate_inputs_under_cap = stage02_config[\"budget\"][\"max_hpo_plan_rows\"] // per_candidate_input_plan_rows\n\n"
        "print(json.dumps({\n"
        "    \"stage_name\": stage02_config[\"stage_name\"],\n"
        "    \"source_stage00_run_id\": stage_inputs[\"stage00_run_id\"],\n"
        "    \"source_stage01_run_id\": stage_inputs[\"stage01_run_id\"],\n"
        "    \"core_hpo_families\": CORE_HPO_FAMILIES,\n"
        "    \"baseline_registry_names\": BASELINE_REGISTRY_NAMES,\n"
        "    \"torch_max_epochs\": torch_defaults[\"epochs\"],\n"
        "    \"torch_early_stopping\": torch_defaults[\"early_stopping\"],\n"
        "    \"profile_counts\": profile_counts,\n"
        "    \"per_candidate_input_plan_rows\": per_candidate_input_plan_rows,\n"
        "    \"max_candidate_inputs_under_cap\": max_candidate_inputs_under_cap,\n"
        "    \"max_hpo_plan_rows\": stage02_config[\"budget\"][\"max_hpo_plan_rows\"],\n"
        "    \"runner_checkpointing_enabled\": stage02_config[\"checkpointing\"][\"enabled\"],\n"
        "    \"holdout_test_contact\": stage02_config[\"holdout_test_contact\"],\n"
        "}, indent=2))\n",
    ),
    (
        "markdown",
        "## Stage 00, Raw Data, And Stage 01 Input Check\n\n"
        "Stage 02 rebuilds train-inner features from Stage 00's frozen training "
        "partition. If the Colab runtime was restarted, this cell downloads the "
        "exact Stage 00 artifacts, exact Stage 01 artifacts, and raw ticker files "
        "from Drive before Stage 02 can run.\n",
    ),
    (
        "code",
        "from lst_models.artifacts import require_artifacts\n\n"
        "def find_unique_drive_child(service, parent_id, name, mime_type=None):\n"
        "    escaped_name = quote_drive_query_value(name)\n"
        "    query_parts = [f\"name = '{escaped_name}'\", f\"'{parent_id}' in parents\", \"trashed = false\"]\n"
        "    if mime_type:\n"
        "        query_parts.append(f\"mimeType = '{mime_type}'\")\n"
        "    response = service.files().list(q=\" and \".join(query_parts), spaces=\"drive\", fields=\"files(id, name, mimeType, size)\", pageSize=10).execute()\n"
        "    matches = response.get(\"files\", [])\n"
        "    if len(matches) != 1:\n"
        "        raise FileNotFoundError(f\"expected exactly one Drive item named {name!r} under parent {parent_id}; found {len(matches)}\")\n"
        "    return matches[0]\n\n"
        "def resolve_drive_folder(service, path_parts):\n"
        "    folder_id = \"root\"\n"
        "    folder_mime = \"application/vnd.google-apps.folder\"\n"
        "    for folder_name in path_parts:\n"
        "        folder = find_unique_drive_child(service, folder_id, folder_name, folder_mime)\n"
        "        folder_id = folder[\"id\"]\n"
        "    return folder_id\n\n"
        "def download_drive_file(service, file_id, output_path):\n"
        "    from googleapiclient.http import MediaIoBaseDownload\n"
        "    output_path.parent.mkdir(parents=True, exist_ok=True)\n"
        "    request = service.files().get_media(fileId=file_id)\n"
        "    with output_path.open(\"wb\") as handle:\n"
        "        downloader = MediaIoBaseDownload(handle, request)\n"
        "        done = False\n"
        "        while not done:\n"
        "            _, done = downloader.next_chunk()\n\n"
        "def get_drive_service_for_input_sync():\n"
        "    try:\n"
        "        from google.colab import auth\n"
        "        from googleapiclient.discovery import build\n"
        "    except ImportError as exc:\n"
        "        raise RuntimeError(\"Drive sync only works inside Colab with Google API dependencies.\") from exc\n"
        "    auth.authenticate_user()\n"
        "    return build(\"drive\", \"v3\")\n\n"
        "def sync_stage_artifacts_from_drive(service, output_dir, path_parts, required_names, label):\n"
        "    run_folder_id = resolve_drive_folder(service, path_parts)\n"
        "    for artifact_name in required_names:\n"
        "        output_path = Path(output_dir) / artifact_name\n"
        "        if output_path.exists():\n"
        "            continue\n"
        "        file_meta = find_unique_drive_child(service, run_folder_id, artifact_name)\n"
        "        download_drive_file(service, file_meta[\"id\"], output_path)\n"
        "        print(f\"downloaded {label}: {artifact_name}\")\n\n"
        "def sync_raw_data_from_drive(service):\n"
        "    with RAW_DATA_MANIFEST_PATH.open(\"r\", encoding=\"utf-8\") as handle:\n"
        "        raw_manifest = yaml.safe_load(handle)\n"
        "    raw_source = raw_manifest[\"raw_source\"]\n"
        "    RAW_DATA_DIR.mkdir(parents=True, exist_ok=True)\n"
        "    for ticker in raw_manifest[\"tickers\"]:\n"
        "        spec = raw_source[\"files\"][ticker]\n"
        "        output_path = RAW_DATA_DIR / spec[\"name\"]\n"
        "        if output_path.exists():\n"
        "            continue\n"
        "        download_drive_file(service, spec[\"file_id\"], output_path)\n"
        "        print(f\"downloaded raw data: {output_path.name}\")\n\n"
        "required_stage00_artifacts = stage02_config[\"inputs\"][\"required_stage00_artifacts\"]\n"
        "required_stage01_artifacts = stage02_config[\"inputs\"][\"required_stage01_artifacts\"]\n"
        "if RUN_STAGE02 or RUN_STAGE02_CHECKPOINT:\n"
        "    service = get_drive_service_for_input_sync()\n"
        "    missing_raw = []\n"
        "    with RAW_DATA_MANIFEST_PATH.open(\"r\", encoding=\"utf-8\") as handle:\n"
        "        raw_manifest = yaml.safe_load(handle)\n"
        "    for ticker in raw_manifest[\"tickers\"]:\n"
        "        raw_path = RAW_DATA_DIR / raw_manifest[\"raw_source\"][\"files\"][ticker][\"name\"]\n"
        "        if not raw_path.exists():\n"
        "            missing_raw.append(raw_path.name)\n"
        "    if missing_raw and RUN_RAW_DATA_SYNC:\n"
        "        print(\"Missing raw data files; syncing from Drive file IDs:\", missing_raw)\n"
        "        sync_raw_data_from_drive(service)\n"
        "    stage00_missing = [name for name in required_stage00_artifacts if not (STAGE00_OUTPUT_DIR / name).exists()]\n"
        "    if stage00_missing and RUN_STAGE00_DRIVE_SYNC:\n"
        "        print(\"Missing Stage 00 artifacts; syncing exact frozen run from Drive.\")\n"
        "        sync_stage_artifacts_from_drive(service, STAGE00_OUTPUT_DIR, STAGE00_DRIVE_PATH_PARTS, stage00_missing, \"stage00\")\n"
        "    stage01_missing = [name for name in required_stage01_artifacts if not (STAGE01_OUTPUT_DIR / name).exists()]\n"
        "    if stage01_missing and RUN_STAGE01_DRIVE_SYNC:\n"
        "        print(\"Missing Stage 01 artifacts; syncing exact frozen run from Drive.\")\n"
        "        sync_stage_artifacts_from_drive(service, STAGE01_OUTPUT_DIR, STAGE01_DRIVE_PATH_PARTS, stage01_missing, \"stage01\")\n"
        "    require_artifacts(STAGE00_OUTPUT_DIR, required_stage00_artifacts)\n"
        "    require_artifacts(STAGE01_OUTPUT_DIR, required_stage01_artifacts)\n"
        "    print(\"Stage 00, raw data, and Stage 01 input checks passed.\")\n"
        "else:\n"
        "    print(\"RUN_STAGE02=False and RUN_STAGE02_CHECKPOINT=False; input sync skipped.\")\n",
    ),
    (
        "markdown",
        "## Stage 02 Checkpoint Archive\n\n"
        "This optional notebook-level checkpoint archives sidecars and input "
        "handoffs. The runner also writes incremental local checkpoints during "
        "formal HPO according to `stage02_config['checkpointing']`.\n",
    ),
    (
        "code",
        "def copy_existing_file(source_path, destination_path, missing_paths):\n"
        "    source_path = Path(source_path)\n"
        "    destination_path = Path(destination_path)\n"
        "    if not source_path.exists():\n"
        "        missing_paths.append(str(source_path))\n"
        "        return\n"
        "    destination_path.parent.mkdir(parents=True, exist_ok=True)\n"
        "    shutil.copy2(source_path, destination_path)\n\n"
        "def assert_stage02_checkpoint_file_scope(output_run_dir=None):\n"
        "    forbidden_prefixes = (\"03_\", \"validation_\", \"test_\", \"holdout_\", \"official_validation_\")\n"
        "    candidate_roots = [STAGE00_OUTPUT_DIR, STAGE01_OUTPUT_DIR]\n"
        "    if output_run_dir is not None:\n"
        "        candidate_roots.append(Path(output_run_dir))\n"
        "    forbidden_files = []\n"
        "    for root in candidate_roots:\n"
        "        if root.exists():\n"
        "            forbidden_files.extend(str(path) for path in root.rglob(\"*\") if path.is_file() and path.name.lower().startswith(forbidden_prefixes))\n"
        "    if forbidden_files:\n"
        "        raise ValueError(\"Stage 02 checkpoint refused official validation/test/holdout files: \" + json.dumps(forbidden_files, indent=2))\n\n"
        "def load_stage02_run_safety(output_run_dir=None):\n"
        "    safety = {\"holdout_test_contact\": False, \"official_validation_for_selection\": False, \"ready_for_stage03\": False, \"source_run_manifest\": None, \"source_stage03_handoff\": None}\n"
        "    if output_run_dir is None:\n"
        "        return safety\n"
        "    output_run_dir = Path(output_run_dir)\n"
        "    run_manifest_path = output_run_dir / \"run_manifest.json\"\n"
        "    if run_manifest_path.exists():\n"
        "        run_manifest = json.loads(run_manifest_path.read_text(encoding=\"utf-8\"))\n"
        "        safety[\"source_run_manifest\"] = str(run_manifest_path)\n"
        "        run_manifest_holdout_contact = run_manifest.get(\"holdout_test_contact\")\n"
        "        if run_manifest_holdout_contact is not False:\n"
        "            raise ValueError(f\"Stage 02 checkpoint requires run manifest holdout_test_contact=false: {run_manifest_path}\")\n"
        "        safety[\"official_validation_for_selection\"] = run_manifest.get(\"official_validation_for_selection\", False)\n"
        "    stage03_handoff_path = output_run_dir / \"02_stage03_handoff.json\"\n"
        "    if stage03_handoff_path.exists():\n"
        "        handoff = json.loads(stage03_handoff_path.read_text(encoding=\"utf-8\"))\n"
        "        safety[\"source_stage03_handoff\"] = str(stage03_handoff_path)\n"
        "        if handoff.get(\"holdout_test_contact\") is not False:\n"
        "            raise ValueError(f\"Stage 02 checkpoint requires handoff holdout_test_contact=false: {stage03_handoff_path}\")\n"
        "        safety[\"ready_for_stage03\"] = bool(handoff.get(\"ready_for_stage03\", False))\n"
        "    return safety\n\n"
        "def get_drive_service_for_checkpoint():\n"
        "    try:\n"
        "        from google.colab import auth\n"
        "        from googleapiclient.discovery import build\n"
        "    except ImportError as exc:\n"
        "        raise RuntimeError(\"Stage 02 checkpoint upload only works inside Colab.\") from exc\n"
        "    auth.authenticate_user()\n"
        "    return build(\"drive\", \"v3\")\n\n"
        "def ensure_drive_path(service, path_parts):\n"
        "    folder_id = \"root\"\n"
        "    folder_mime = \"application/vnd.google-apps.folder\"\n"
        "    for part in path_parts:\n"
        "        matches = service.files().list(q=f\"name = '{quote_drive_query_value(part)}' and '{folder_id}' in parents and trashed = false and mimeType = '{folder_mime}'\", fields=\"files(id, name, webViewLink)\", pageSize=10).execute().get(\"files\", [])\n"
        "        if len(matches) == 1:\n"
        "            folder_id = matches[0][\"id\"]\n"
        "        elif len(matches) == 0:\n"
        "            created = service.files().create(body={\"name\": part, \"mimeType\": folder_mime, \"parents\": [folder_id]}, fields=\"id, name, webViewLink\").execute()\n"
        "            folder_id = created[\"id\"]\n"
        "        else:\n"
        "            raise RuntimeError(f\"Duplicate Drive folders named {part!r} under parent {folder_id}\")\n"
        "    return folder_id\n\n"
        "def upload_checkpoint_archive(service, folder_id, archive_path):\n"
        "    from googleapiclient.http import MediaFileUpload\n"
        "    media = MediaFileUpload(str(archive_path), mimetype=\"application/zip\", resumable=True)\n"
        "    return service.files().create(body={\"name\": archive_path.name, \"parents\": [folder_id]}, media_body=media, fields=\"id, name, size, webViewLink\").execute()\n\n"
        "def build_stage02_checkpoint_archive(label, output_run_dir=None):\n"
        "    checkpoint_timestamp = datetime.now(timezone.utc).strftime(\"%Y%m%dT%H%M%S_%fZ\")\n"
        "    checkpoint_dir = CHECKPOINT_ROOT / f\"{checkpoint_timestamp}_{label}\"\n"
        "    checkpoint_dir.mkdir(parents=True, exist_ok=False)\n"
        "    missing_paths = []\n"
        "    checkpoint_stage01_artifacts = stage02_config[\"inputs\"][\"required_stage01_artifacts\"]\n"
        "    checkpoint_stage00_artifacts = stage02_config[\"inputs\"][\"required_stage00_artifacts\"]\n"
        "    assert_stage02_checkpoint_file_scope(output_run_dir)\n"
        "    run_safety = load_stage02_run_safety(output_run_dir)\n"
        "    sidecar_dir = checkpoint_dir / \"sidecars\"\n"
        "    for source_path in [STAGE_CONFIG_PATH, PROTOCOL_PATH, NOTEBOOK_PATH, STAGE_ENTRYPOINT_PATH, RAW_DATA_MANIFEST_PATH]:\n"
        "        copy_existing_file(source_path, sidecar_dir / source_path.name, missing_paths)\n"
        "    for family in CORE_HPO_FAMILIES:\n"
        "        source_path = PROJECT_ROOT / stage02_config[\"hpo_families\"][family][\"search_space\"]\n"
        "        copy_existing_file(source_path, checkpoint_dir / \"search_spaces\" / family / \"search_space.yaml\", missing_paths)\n"
        "    for artifact_name in checkpoint_stage00_artifacts:\n"
        "        copy_existing_file(STAGE00_OUTPUT_DIR / artifact_name, checkpoint_dir / \"stage00_inputs\" / artifact_name, missing_paths)\n"
        "    for artifact_name in checkpoint_stage01_artifacts:\n"
        "        copy_existing_file(STAGE01_OUTPUT_DIR / artifact_name, checkpoint_dir / \"stage01_inputs\" / artifact_name, missing_paths)\n"
        "    if output_run_dir is not None:\n"
        "        output_run_dir = Path(output_run_dir)\n"
        "        if output_run_dir.exists():\n"
        "            shutil.copytree(output_run_dir, checkpoint_dir / \"stage02_run\", dirs_exist_ok=True)\n"
        "        else:\n"
        "            missing_paths.append(str(output_run_dir))\n"
        "    manifest = {\n"
        "        \"route\": ROUTE,\n"
        "        \"stage_name\": STAGE_NAME,\n"
        "        \"checkpoint_label\": label,\n"
        "        \"checkpoint_timestamp_utc\": checkpoint_timestamp,\n"
        "        \"source_stage00_run_id\": STAGE00_RUN_ID,\n"
        "        \"source_stage01_run_id\": STAGE01_RUN_ID,\n"
        "        \"stage02_run_id\": STAGE02_RUN_ID,\n"
        "        \"expected_stage02_output_dir\": str(STAGE02_OUTPUT_DIR),\n"
        "        \"superseded_stage02_run_ids\": SUPERSEDED_STAGE02_RUN_IDS,\n"
        "        \"checkpoint_drive_path_parts\": CHECKPOINT_DRIVE_PATH_PARTS,\n"
        "        \"included_stage00_artifacts\": [name for name in checkpoint_stage00_artifacts if (STAGE00_OUTPUT_DIR / name).exists()],\n"
        "        \"included_stage01_artifacts\": [name for name in checkpoint_stage01_artifacts if (STAGE01_OUTPUT_DIR / name).exists()],\n"
        "        \"included_output_run_dir\": str(output_run_dir) if output_run_dir is not None else None,\n"
        "        \"source_run_manifest\": run_safety[\"source_run_manifest\"],\n"
        "        \"source_stage03_handoff\": run_safety[\"source_stage03_handoff\"],\n"
        "        \"missing_paths\": missing_paths,\n"
        "        \"holdout_test_contact\": run_safety[\"holdout_test_contact\"],\n"
        "        \"official_validation_for_selection\": run_safety[\"official_validation_for_selection\"],\n"
        "        \"ready_for_stage03\": run_safety[\"ready_for_stage03\"],\n"
        "    }\n"
        "    manifest_path = checkpoint_dir / \"stage02_checkpoint_manifest.json\"\n"
        "    manifest_path.write_text(json.dumps(manifest, indent=2), encoding=\"utf-8\")\n"
        "    archive_path = Path(shutil.make_archive(str(checkpoint_dir), \"zip\", root_dir=checkpoint_dir))\n"
        "    return archive_path, manifest\n\n"
        "def write_stage02_drive_checkpoint(label, output_run_dir=None):\n"
        "    archive_path, manifest = build_stage02_checkpoint_archive(label, output_run_dir=output_run_dir)\n"
        "    service = get_drive_service_for_checkpoint()\n"
        "    folder_id = ensure_drive_path(service, CHECKPOINT_DRIVE_PATH_PARTS)\n"
        "    uploaded = upload_checkpoint_archive(service, folder_id, archive_path)\n"
        "    print(\"Stage 02 checkpoint archive:\", archive_path)\n"
        "    print(json.dumps({\"checkpoint_manifest\": manifest, \"drive_upload\": uploaded}, indent=2))\n"
        "    return archive_path, uploaded\n\n"
        "if RUN_STAGE02_CHECKPOINT:\n"
        "    write_stage02_drive_checkpoint(\"pre_stage02\")\n"
        "else:\n"
        "    print(\"RUN_STAGE02_CHECKPOINT=False; no Stage 02 checkpoint archive uploaded.\")\n",
    ),
    (
        "markdown",
        "## Run Stage 02\n\n"
        "The package-backed stage entry point is "
        "`lst_models.stages.model_hpo_train_inner.run_stage`. The committed "
        "notebook remains inert by default.\n",
    ),
    (
        "code",
        "if RUN_STAGE02:\n"
        "    try:\n"
        "        from lst_models.stages.model_hpo_train_inner import run_stage\n"
        "    except ModuleNotFoundError as exc:\n"
        "        raise ModuleNotFoundError(\"Missing Stage 02 package entry point: src/lst_models/stages/model_hpo_train_inner.py.\") from exc\n"
        "    result = run_stage(stage02_config)\n"
        "    display(result)\n"
        "    if Path(result.output_dir).name != STAGE02_RUN_ID:\n"
        "        raise RuntimeError(f\"Stage 02 run id mismatch: {Path(result.output_dir).name} != {STAGE02_RUN_ID}\")\n"
        "    if Path(result.output_dir) != STAGE02_OUTPUT_DIR:\n"
        "        raise RuntimeError(f\"Stage 02 output dir mismatch: {Path(result.output_dir)} != {STAGE02_OUTPUT_DIR}\")\n"
        "    if RUN_STAGE02_CHECKPOINT:\n"
        "        write_stage02_drive_checkpoint(\"post_stage02\", output_run_dir=Path(result.output_dir))\n"
        "else:\n"
        "    print(\"RUN_STAGE02=False; Stage 02 train-inner HPO not executed.\")\n",
    ),
    (
        "markdown",
        "## Stage 02 Drive Result Backup\n\n"
        "After `run_stage` returns, this cell saves the Stage 02 run folder to "
        "`My Drive/lst_models/results/02_model_hpo_train_inner/<stage02_run_id>/`.\n",
    ),
    (
        "code",
        "def get_drive_service_for_stage02_result_backup():\n"
        "    try:\n"
        "        from google.colab import auth\n"
        "        from googleapiclient.discovery import build\n"
        "    except ImportError as exc:\n"
        "        raise RuntimeError(\"RUN_STAGE02_DRIVE_BACKUP=True only works inside Colab with Google API dependencies.\") from exc\n"
        "    auth.authenticate_user()\n"
        "    return build(\"drive\", \"v3\")\n\n"
        "def find_stage02_result_drive_child(service, parent_id, name, mime_type=None):\n"
        "    escaped_name = quote_drive_query_value(name)\n"
        "    query_parts = [f\"name = '{escaped_name}'\", f\"'{parent_id}' in parents\", \"trashed = false\"]\n"
        "    if mime_type:\n"
        "        query_parts.append(f\"mimeType = '{mime_type}'\")\n"
        "    response = service.files().list(q=\" and \".join(query_parts), fields=\"files(id, name, mimeType, size, webViewLink)\", supportsAllDrives=True, includeItemsFromAllDrives=True, pageSize=10).execute()\n"
        "    return response.get(\"files\", [])\n\n"
        "def ensure_stage02_result_drive_folder(service, parent_id, name):\n"
        "    folder_mime = \"application/vnd.google-apps.folder\"\n"
        "    matches = find_stage02_result_drive_child(service, parent_id, name, folder_mime)\n"
        "    if len(matches) == 1:\n"
        "        return matches[0][\"id\"]\n"
        "    if len(matches) > 1:\n"
        "        raise RuntimeError(f\"Duplicate Drive folders named {name!r} under parent {parent_id}\")\n"
        "    created = service.files().create(body={\"name\": name, \"mimeType\": folder_mime, \"parents\": [parent_id]}, fields=\"id, name, webViewLink\", supportsAllDrives=True).execute()\n"
        "    print(\"Created Drive folder:\", name, created.get(\"webViewLink\"))\n"
        "    return created[\"id\"]\n\n"
        "def ensure_stage02_result_drive_path(service, path_parts):\n"
        "    folder_id = \"root\"\n"
        "    for part in path_parts:\n"
        "        folder_id = ensure_stage02_result_drive_folder(service, folder_id, part)\n"
        "    return folder_id\n\n"
        "def ensure_stage02_result_drive_subpath(service, root_folder_id, relative_parent_parts):\n"
        "    folder_id = root_folder_id\n"
        "    for part in relative_parent_parts:\n"
        "        folder_id = ensure_stage02_result_drive_folder(service, folder_id, part)\n"
        "    return folder_id\n\n"
        "def upload_or_update_stage02_result_file(service, root_parent_id, run_dir, local_path):\n"
        "    from googleapiclient.http import MediaFileUpload\n"
        "    relative_path = local_path.relative_to(run_dir)\n"
        "    if any(part in {\"\", \".\", \"..\"} for part in relative_path.parts):\n"
        "        raise ValueError(f\"Unsafe Stage 02 backup relative path: {relative_path}\")\n"
        "    parent_parts = [] if relative_path.parent == Path(\".\") else list(relative_path.parent.parts)\n"
        "    parent_id = ensure_stage02_result_drive_subpath(service, root_parent_id, parent_parts)\n"
        "    matches = find_stage02_result_drive_child(service, parent_id, relative_path.name)\n"
        "    media = MediaFileUpload(str(local_path), resumable=True)\n"
        "    if len(matches) == 0:\n"
        "        uploaded = service.files().create(body={\"name\": relative_path.name, \"parents\": [parent_id]}, media_body=media, fields=\"id, name, size, webViewLink\", supportsAllDrives=True).execute()\n"
        "        action = \"uploaded\"\n"
        "    elif len(matches) == 1:\n"
        "        uploaded = service.files().update(fileId=matches[0][\"id\"], media_body=media, fields=\"id, name, size, webViewLink\", supportsAllDrives=True).execute()\n"
        "        action = \"updated\"\n"
        "    else:\n"
        "        raise RuntimeError(f\"Duplicate Drive files named {relative_path.name!r} under parent {parent_id}\")\n"
        "    uploaded = dict(uploaded)\n"
        "    uploaded[\"relative_path\"] = relative_path.as_posix()\n"
        "    uploaded[\"parent_relative_path\"] = \"\" if not parent_parts else \"/\".join(parent_parts)\n"
        "    print(f\"{action}: {relative_path.as_posix()}\")\n"
        "    return uploaded\n\n"
        "def assert_stage02_result_backup_scope(run_dir):\n"
        "    forbidden_prefixes = (\"03_\", \"validation_\", \"test_\", \"holdout_\", \"official_validation_\")\n"
        "    forbidden_files = [str(path) for path in run_dir.rglob(\"*\") if path.is_file() and path.name.lower().startswith(forbidden_prefixes)]\n"
        "    if forbidden_files:\n"
        "        raise ValueError(\"Stage 02 result backup refused possible official validation/test/holdout files: \" + json.dumps(forbidden_files, indent=2))\n\n"
        "def backup_stage02_results_to_drive(output_run_dir):\n"
        "    run_dir = Path(output_run_dir)\n"
        "    if run_dir.name != STAGE02_RUN_ID:\n"
        "        raise ValueError(f\"Stage 02 backup run id mismatch: {run_dir.name} != {STAGE02_RUN_ID}\")\n"
        "    if not run_dir.exists():\n"
        "        raise FileNotFoundError(f\"Stage 02 output folder not found: {run_dir}\")\n"
        "    required_stage02_files = [\n"
        "        stage02_config[\"outputs\"][\"manifest\"],\n"
        "        stage02_config[\"outputs\"][\"artifact_inventory\"],\n"
        "        stage02_config[\"outputs\"][\"summary\"],\n"
        "        stage02_config[\"outputs\"][\"hpo_plan_ledger\"],\n"
        "        stage02_config[\"outputs\"][\"hpo_trial_ledger\"],\n"
        "        stage02_config[\"outputs\"][\"hpo_summary\"],\n"
        "        stage02_config[\"outputs\"][\"baseline_control_summary\"],\n"
        "        stage02_config[\"outputs\"][\"frozen_candidate\"],\n"
        "        stage02_config[\"outputs\"][\"frozen_candidate_markdown\"],\n"
        "        stage02_config[\"outputs\"][\"best_params_by_family\"],\n"
        "        stage02_config[\"outputs\"][\"stage03_handoff\"],\n"
        "    ]\n"
        "    missing = [name for name in required_stage02_files if not (run_dir / name).exists()]\n"
        "    if missing:\n"
        "        raise FileNotFoundError(f\"Missing required Stage 02 artifacts before Drive backup: {missing}\")\n"
        "    run_manifest_path = run_dir / stage02_config[\"outputs\"][\"manifest\"]\n"
        "    run_manifest = json.loads(run_manifest_path.read_text(encoding=\"utf-8\"))\n"
        "    if run_manifest.get(\"stage02_run_id\") != STAGE02_RUN_ID:\n"
        "        raise ValueError(f\"Stage 02 result backup requires run_manifest stage02_run_id={STAGE02_RUN_ID}: {run_manifest_path}\")\n"
        "    if run_manifest.get(\"holdout_test_contact\") is not False:\n"
        "        raise ValueError(f\"Stage 02 result backup requires holdout_test_contact=false: {run_manifest_path}\")\n"
        "    if run_manifest.get(\"official_validation_for_selection\", False) is not False:\n"
        "        raise ValueError(f\"Stage 02 result backup requires official_validation_for_selection=false: {run_manifest_path}\")\n"
        "    stage03_handoff_path = run_dir / stage02_config[\"outputs\"][\"stage03_handoff\"]\n"
        "    stage03_handoff = json.loads(stage03_handoff_path.read_text(encoding=\"utf-8\"))\n"
        "    if stage03_handoff.get(\"holdout_test_contact\") is not False:\n"
        "        raise ValueError(f\"Stage 02 result backup requires handoff holdout_test_contact=false: {stage03_handoff_path}\")\n"
        "    assert_stage02_result_backup_scope(run_dir)\n"
        "    drive_path_parts = STAGE02_DRIVE_RESULT_PATH_PARTS + [run_dir.name]\n"
        "    service = get_drive_service_for_stage02_result_backup()\n"
        "    drive_folder_id = ensure_stage02_result_drive_path(service, drive_path_parts)\n"
        "    backup_manifest_path = run_dir / \"drive_backup_manifest.json\"\n"
        "    local_files = sorted(path for path in run_dir.rglob(\"*\") if path.is_file() and path.name != backup_manifest_path.name)\n"
        "    uploads = [upload_or_update_stage02_result_file(service, drive_folder_id, run_dir, path) for path in local_files]\n"
        "    backup_manifest = {\n"
        "        \"stage_name\": STAGE_NAME,\n"
        "        \"run_id\": run_dir.name,\n"
        "        \"stage_run_id\": run_dir.name,\n"
        "        \"stage02_run_id\": run_dir.name,\n"
        "        \"superseded_stage02_run_ids\": SUPERSEDED_STAGE02_RUN_IDS,\n"
        "        \"local_output_dir\": str(run_dir),\n"
        "        \"stage02_output_dir\": str(run_dir),\n"
        "        \"drive_path\": \"My Drive/\" + \"/\".join(drive_path_parts),\n"
        "        \"drive_path_parts\": drive_path_parts,\n"
        "        \"drive_folder_id\": drive_folder_id,\n"
        "        \"uploaded_file_names\": [upload[\"name\"] for upload in uploads],\n"
        "        \"uploaded_relative_paths\": [upload[\"relative_path\"] for upload in uploads],\n"
        "        \"uploaded_files\": uploads,\n"
        "        \"sync_timestamp_utc\": datetime.now(timezone.utc).isoformat(),\n"
        "        \"holdout_test_contact\": run_manifest.get(\"holdout_test_contact\"),\n"
        "        \"official_validation_for_selection\": run_manifest.get(\"official_validation_for_selection\"),\n"
        "        \"ready_for_stage03\": stage03_handoff.get(\"ready_for_stage03\"),\n"
        "    }\n"
        "    backup_manifest_path.write_text(json.dumps(backup_manifest, indent=2), encoding=\"utf-8\")\n"
        "    manifest_upload = upload_or_update_stage02_result_file(service, drive_folder_id, run_dir, backup_manifest_path)\n"
        "    backup_manifest[\"uploaded_files\"].append(manifest_upload)\n"
        "    backup_manifest[\"uploaded_file_names\"].append(manifest_upload[\"name\"])\n"
        "    backup_manifest[\"uploaded_relative_paths\"].append(manifest_upload[\"relative_path\"])\n"
        "    backup_manifest_path.write_text(json.dumps(backup_manifest, indent=2), encoding=\"utf-8\")\n"
        "    upload_or_update_stage02_result_file(service, drive_folder_id, run_dir, backup_manifest_path)\n"
        "    print(\"stage_run_id:\", backup_manifest[\"stage_run_id\"])\n"
        "    print(\"drive_path:\", backup_manifest[\"drive_path\"])\n"
        "    print(\"drive_folder_id:\", backup_manifest[\"drive_folder_id\"])\n"
        "    print(json.dumps(backup_manifest, indent=2))\n"
        "    return backup_manifest\n\n"
        "if RUN_STAGE02_DRIVE_BACKUP and RUN_STAGE02:\n"
        "    if \"result\" not in globals():\n"
        "        raise RuntimeError(\"RUN_STAGE02_DRIVE_BACKUP=True requires running Stage 02 first.\")\n"
        "    stage02_drive_backup_manifest = backup_stage02_results_to_drive(result.output_dir)\n"
        "else:\n"
        "    print(\"RUN_STAGE02_DRIVE_BACKUP is disabled or RUN_STAGE02=False; no Stage 02 result backup uploaded.\")\n",
    ),
    (
        "markdown",
        "## Artifact Display\n\n"
        "After an approved run, display only Stage 02 artifacts from "
        "`result.output_dir`. Do not scan for a latest run.\n",
    ),
    (
        "code",
        "if RUN_ARTIFACT_DISPLAY:\n"
        "    import pandas as pd\n\n"
        "    if \"result\" not in globals():\n"
        "        raise RuntimeError(\"RUN_ARTIFACT_DISPLAY=True requires running Stage 02 first.\")\n"
        "    run_dir = Path(result.output_dir)\n"
        "    inventory_path = run_dir / \"artifact_inventory.csv\"\n"
        "    summary_path = run_dir / \"02_model_hpo_train_inner_summary.csv\"\n"
        "    trial_ledger_path = run_dir / \"02_hpo_trial_ledger.csv\"\n"
        "    hpo_summary_path = run_dir / \"02_hpo_summary.csv\"\n"
        "    baseline_summary_path = run_dir / \"02_baseline_control_summary.csv\"\n"
        "    frozen_candidate_path = run_dir / \"02_frozen_candidate.json\"\n"
        "    handoff_path = run_dir / \"02_stage03_handoff.json\"\n"
        "    for path in [inventory_path, summary_path, trial_ledger_path, hpo_summary_path, baseline_summary_path, frozen_candidate_path, handoff_path]:\n"
        "        require_path(path)\n"
        "    display(pd.read_csv(inventory_path))\n"
        "    display(pd.read_csv(summary_path))\n"
        "    display(pd.read_csv(trial_ledger_path).head(20))\n"
        "    display(pd.read_csv(hpo_summary_path))\n"
        "    display(pd.read_csv(baseline_summary_path).head(20))\n"
        "    with frozen_candidate_path.open(\"r\", encoding=\"utf-8\") as handle:\n"
        "        frozen_candidate = json.load(handle)\n"
        "    with handoff_path.open(\"r\", encoding=\"utf-8\") as handle:\n"
        "        stage03_handoff = json.load(handle)\n"
        "    assert frozen_candidate[\"holdout_test_contact\"] is False\n"
        "    assert stage03_handoff[\"holdout_test_contact\"] is False\n"
        "    print(json.dumps(frozen_candidate, indent=2))\n"
        "    print(json.dumps(stage03_handoff, indent=2))\n"
        "else:\n"
        "    print(\"RUN_ARTIFACT_DISPLAY=False; no Stage 02 artifacts displayed.\")\n",
    ),
    (
        "markdown",
        "## Interpretation Guard\n\n"
        "Allowed wording after formal HPO runs:\n\n"
        "- Stage 02 train-inner HPO completed for approved families.\n"
        "- Stage 02 primary and fallback candidates were frozen from train-inner HPO.\n"
        "- Stage 02 is ready for Stage 03 only if `02_stage03_handoff.json` records "
        "`ready_for_stage03=true`.\n\n"
        "Do not claim a final model, official validation winner, holdout winner, "
        "or test winner from this notebook.\n",
    ),
]


def build_notebook() -> nbf.NotebookNode:
    nb = nbf.v4.new_notebook()
    nb.metadata = {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "pygments_lexer": "ipython3"},
        "colab": {"provenance": []},
    }
    nb.cells = []
    for cell_type, cell_source in CELL_SPECS:
        if cell_type == "markdown":
            cell = nbf.v4.new_markdown_cell(cell_source)
        elif cell_type == "code":
            cell = nbf.v4.new_code_cell(cell_source)
            cell.outputs = []
            cell.execution_count = None
        else:
            raise ValueError(f"unsupported cell type: {cell_type}")
        cell.metadata = {}
        nb.cells.append(cell)
    return nb


def main() -> None:
    root = Path(__file__).resolve().parents[2]
    output_path = root / "notebooks" / "02_model_hpo_train_inner_colab.ipynb"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(build_notebook(), output_path)
    print(output_path)


if __name__ == "__main__":
    main()
