from __future__ import annotations

from pathlib import Path

import nbformat as nbf


CELL_SPECS = [
    (
        "markdown",
        "# Stage 03 - Frozen Official-Validation Readout\n\n"
        "Route: `lst_models` V2\n"
        "Scope: `validation_only` (no test or holdout contact; official "
        "validation contacted exactly once per frozen seed and candidate)\n"
        "User-facing notebook: `notebooks/03_frozen_validation_readout_colab.ipynb`\n\n"
        "This notebook executes the ONE-SHOT Stage 03 readout pre-registered in "
        "`docs/protocols/03_frozen_validation_readout_protocol.md`. It refits "
        "the frozen Stage 02 primary candidate per frozen seed on all eligible "
        "official-train rows and scores all eligible official-validation rows "
        "exactly once per seed. Official validation is never used for "
        "selection, tuning, early stopping, thresholding, or ranking, and "
        "`no_final_model_selected=true` is retained in every output.\n",
    ),
    (
        "markdown",
        "## Frozen Protocol Summary\n\n"
        "- Refit recipe (D1): mechanism-frozen chronological-tail early "
        "stopping carved from the refit rows only; the scored validation rows "
        "are never an early-stopping eval set.\n"
        "- Row policy (D2): refit on ALL eligible official-train rows; score "
        "ALL eligible official-validation rows (natural label distribution).\n"
        "- Frozen seeds: `[101, 202]`, gate-checked against the Stage 02 "
        "frozen candidate seed policy.\n"
        "- Predeclared criteria (judged on the seed-aggregate mean): both "
        "same-row baseline deltas positive AND positive-ticker floor >= 3.\n"
        "- Fallback policy: mechanical failures only, never weak metrics, and "
        "never after the first scoring event.\n"
        "- Stage 02 absolute metrics and Stage 03 absolute metrics are NOT "
        "comparable (equal-allocation subsamples vs natural distribution; "
        "Zadrozny 2004). Only Stage 03 same-row deltas support claims.\n",
    ),
    (
        "markdown",
        "## Expected Artifacts\n\n"
        "When `RUN_STAGE03=True`, the runner writes:\n\n"
        "```text\n"
        "results/03_frozen_validation_readout/<run_id>/\n"
        "  03_validation_readout.csv\n"
        "  03_per_ticker_readout.csv\n"
        "  03_seed_summary.csv\n"
        "  03_same_row_baselines.csv\n"
        "  03_validation_predictions.csv\n"
        "  03_decision_record.json\n"
        "  run_manifest.json\n"
        "  artifact_inventory.csv\n"
        "```\n\n"
        "The durable-save cell uploads the run folder plus "
        "`drive_backup_manifest.json` to "
        "`My Drive/lst_models/results/03_frozen_validation_readout/<run_id>/`. "
        "Per-seed recovery checkpoints are mirrored to "
        "`My Drive/lst_models/checkpoints/03_frozen_validation_readout/<run_id>/`.\n",
    ),
    (
        "code",
        "from pathlib import Path\n"
        "from datetime import datetime, timezone\n"
        "import importlib\n"
        "import json\n"
        "import shutil\n"
        "import subprocess\n"
        "import sys\n"
        "import threading\n"
        "import time\n"
        "import zipfile\n\n"
        "RUN_PROJECT_BOOTSTRAP = True\n"
        "PROJECT_BOOTSTRAP_MODE = \"github_commit\"  # github_commit | manual_upload | already_present\n\n"
        "PROJECT_REPO_URL = \"https://github.com/zkc768/lstm-zhang.git\"\n"
        "PROJECT_REPO_COMMIT = \"142646000a7bdd11f0985e915fc627a9eea101fd\"\n"
        "PROJECT_ROOT = Path(\"/content/lst_models\")\n\n"
        "RUN_STAGE00_DRIVE_SYNC = True\n"
        "RUN_STAGE01_DRIVE_SYNC = True\n"
        "RUN_STAGE02_DRIVE_SYNC = True\n"
        "RUN_RAW_DATA_SYNC = True\n"
        "RUN_STAGE03_CHECKPOINT_MIRROR = True\n"
        "RUN_STAGE03_DRIVE_BACKUP = True\n"
        "RUN_STAGE03 = False\n"
        "RUN_ARTIFACT_DISPLAY = False\n\n"
        "# Exact-run resume (protocol section 11): fill ONLY to complete a crashed\n"
        "# readout. A resumed run skips every recorded scoring event; a fresh run\n"
        "# keeps this empty.\n"
        "RESUME_STAGE03_RUN_ID = \"\"\n"
        "RESUME_STAGE03_CHECKPOINT_DIR = \"\"  # defaults to CHECKPOINT_ROOT / RESUME_STAGE03_RUN_ID\n\n"
        "STAGE_NAME = \"03_frozen_validation_readout\"\n"
        "ROUTE = \"lst_models\"\n"
        "SCOPE = \"validation_only\"\n"
        "HOLDOUT_TEST_CONTACT = False\n"
        "OFFICIAL_VALIDATION_CONTACT = True\n"
        "OFFICIAL_VALIDATION_FOR_SELECTION = False\n"
        "STAGE00_RUN_ID = \"20260610_051705_347450\"\n"
        "STAGE01_RUN_ID = \"20260610_075002\"\n"
        "STAGE02_RUN_ID = \"20260610_082130_797479\"\n"
        "SUPERSEDED_STAGE02_RUN_IDS = [\"20260609_100637_704705\", \"20260610_010019_507648\"]\n"
        "FROZEN_SEEDS = [101, 202]\n"
        "STAGE00_OUTPUT_DIR = Path(\"/content/lst_models_results/00_data_split_label_freeze\") / STAGE00_RUN_ID\n"
        "STAGE01_OUTPUT_DIR = Path(\"/content/lst_models_results/01_feature_window_search\") / STAGE01_RUN_ID\n"
        "STAGE02_OUTPUT_DIR = Path(\"/content/lst_models_results/02_model_hpo_train_inner\") / STAGE02_RUN_ID\n"
        "STAGE00_DRIVE_PATH_PARTS = [\"lst_models\", \"results\", \"00_data_split_label_freeze\", STAGE00_RUN_ID]\n"
        "STAGE01_DRIVE_PATH_PARTS = [\"lst_models\", \"results\", \"01_feature_window_search\", STAGE01_RUN_ID]\n"
        "STAGE02_DRIVE_PATH_PARTS = [\"lst_models\", \"results\", \"02_model_hpo_train_inner\", STAGE02_RUN_ID]\n"
        "OUTPUT_DIR = Path(\"/content/lst_models_results/03_frozen_validation_readout\")\n"
        "STAGE03_DRIVE_RESULT_PATH_PARTS = [\"lst_models\", \"results\", \"03_frozen_validation_readout\"]\n"
        "RAW_DATA_DIR = Path(\"/content/lst_models_raw_stock_data\")\n"
        "CHECKPOINT_ROOT = Path(\"/content/lst_models_checkpoints/03_frozen_validation_readout\")\n"
        "CHECKPOINT_DRIVE_BASE_PARTS = [\"lst_models\", \"checkpoints\", \"03_frozen_validation_readout\"]\n"
        "REQUIRED_STAGE03_OUTPUTS = [\n"
        "    \"03_validation_readout.csv\",\n"
        "    \"03_per_ticker_readout.csv\",\n"
        "    \"03_seed_summary.csv\",\n"
        "    \"03_same_row_baselines.csv\",\n"
        "    \"03_validation_predictions.csv\",\n"
        "    \"03_decision_record.json\",\n"
        "    \"run_manifest.json\",\n"
        "    \"artifact_inventory.csv\",\n"
        "]\n\n"
        "if RUN_STAGE03 and \"<\" in STAGE02_RUN_ID:\n"
        "    raise ValueError(\"fill STAGE02_RUN_ID with the superseding Stage 02 run id before executing Stage 03\")\n"
        "if STAGE02_RUN_ID in SUPERSEDED_STAGE02_RUN_IDS:\n"
        "    raise ValueError(f\"superseded Stage 02 run id must not be pinned: {STAGE02_RUN_ID}\")\n\n"
        "def quote_drive_query_value(value):\n"
        "    return str(value).replace(\"\\\\\", \"\\\\\\\\\").replace(\"'\", \"\\\\'\")\n\n"
        "def run_cmd(args, cwd=None):\n"
        "    print(\"+\", \" \".join(str(arg) for arg in args))\n"
        "    subprocess.run(args, cwd=cwd, check=True)\n\n"
        "def looks_like_project_root(path):\n"
        "    return (\n"
        "        (path / \"configs\" / \"stages\" / \"03_frozen_validation_readout.yaml\").exists()\n"
        "        and (path / \"docs\" / \"protocols\" / \"03_frozen_validation_readout_protocol.md\").exists()\n"
        "        and (path / \"notebooks\" / \"03_frozen_validation_readout_colab.ipynb\").exists()\n"
        "        and (path / \"src\" / \"lst_models\" / \"stages\" / \"frozen_validation_readout.py\").exists()\n"
        "    )\n\n"
        "def safe_extract_project_zip(zip_path):\n"
        "    destination = Path(\"/content\").resolve()\n"
        "    with zipfile.ZipFile(zip_path) as archive:\n"
        "        for member in archive.infolist():\n"
        "            member_path = Path(member.filename)\n"
        "            if member_path.is_absolute() or \"..\" in member_path.parts:\n"
        "                raise ValueError(f\"Unsafe path in uploaded zip: {member.filename}\")\n"
        "            target = (destination / member_path).resolve()\n"
        "            if target != destination and destination not in target.parents:\n"
        "                raise ValueError(f\"Unsafe path in uploaded zip: {member.filename}\")\n"
        "        archive.extractall(destination)\n"
        "    for candidate in [Path(\"/content/lst_models\"), Path(\"/content\") / zip_path.stem]:\n"
        "        if looks_like_project_root(candidate):\n"
        "            return candidate\n"
        "    raise FileNotFoundError(\"No lst_models project root found after zip extraction.\")\n\n"
        "def upload_and_extract_project_zip():\n"
        "    try:\n"
        "        from google.colab import files\n"
        "    except ImportError as exc:\n"
        "        raise RuntimeError(\"manual_upload mode only works inside Colab.\") from exc\n"
        "    uploaded = files.upload()\n"
        "    zip_names = [name for name in uploaded if name.endswith(\".zip\")]\n"
        "    if not zip_names:\n"
        "        raise ValueError(\"Upload a .zip file containing the lst_models project folder.\")\n"
        "    return safe_extract_project_zip(Path(\"/content\") / zip_names[0])\n\n"
        "if RUN_PROJECT_BOOTSTRAP:\n"
        "    if PROJECT_BOOTSTRAP_MODE == \"github_commit\":\n"
        "        if \"<\" in PROJECT_REPO_COMMIT:\n"
        "            raise ValueError(\"fill PROJECT_REPO_COMMIT with the Stage 03 full-bundle commit before bootstrapping\")\n"
        "        if (PROJECT_ROOT / \".git\").exists():\n"
        "            run_cmd([\"git\", \"fetch\", \"origin\"], cwd=PROJECT_ROOT)\n"
        "            run_cmd([\"git\", \"checkout\", PROJECT_REPO_COMMIT], cwd=PROJECT_ROOT)\n"
        "        else:\n"
        "            run_cmd([\"git\", \"clone\", PROJECT_REPO_URL, str(PROJECT_ROOT)])\n"
        "            run_cmd([\"git\", \"checkout\", PROJECT_REPO_COMMIT], cwd=PROJECT_ROOT)\n"
        "        actual_commit = subprocess.check_output([\"git\", \"rev-parse\", \"HEAD\"], cwd=PROJECT_ROOT, text=True).strip()\n"
        "        assert actual_commit == PROJECT_REPO_COMMIT, (actual_commit, PROJECT_REPO_COMMIT)\n"
        "    elif PROJECT_BOOTSTRAP_MODE == \"manual_upload\":\n"
        "        PROJECT_ROOT = upload_and_extract_project_zip()\n"
        "    elif PROJECT_BOOTSTRAP_MODE == \"already_present\":\n"
        "        pass\n"
        "    else:\n"
        "        raise ValueError(\"PROJECT_BOOTSTRAP_MODE must be github_commit, manual_upload, or already_present\")\n\n"
        "STAGE_CONFIG_PATH = PROJECT_ROOT / \"configs\" / \"stages\" / \"03_frozen_validation_readout.yaml\"\n"
        "PROTOCOL_PATH = PROJECT_ROOT / \"docs\" / \"protocols\" / \"03_frozen_validation_readout_protocol.md\"\n"
        "NOTEBOOK_PATH = PROJECT_ROOT / \"notebooks\" / \"03_frozen_validation_readout_colab.ipynb\"\n"
        "STAGE_ENTRYPOINT_PATH = PROJECT_ROOT / \"src\" / \"lst_models\" / \"stages\" / \"frozen_validation_readout.py\"\n"
        "RAW_DATA_MANIFEST_PATH = PROJECT_ROOT / \"configs\" / \"lst_models_data.yaml\"\n"
        "REQUIRED_PROJECT_FILES = [STAGE_CONFIG_PATH, PROTOCOL_PATH, NOTEBOOK_PATH, STAGE_ENTRYPOINT_PATH, RAW_DATA_MANIFEST_PATH]\n"
        "missing_project_files = [path for path in REQUIRED_PROJECT_FILES if not path.exists()]\n"
        "if missing_project_files:\n"
        "    missing_text = \"\\n\".join(f\"- {path}\" for path in missing_project_files)\n"
        "    raise FileNotFoundError(\"Stage 03 bootstrap target is missing required files:\\n\" + missing_text)\n\n"
        "SRC_PATH = PROJECT_ROOT / \"src\"\n"
        "if str(SRC_PATH) not in sys.path:\n"
        "    sys.path.insert(0, str(SRC_PATH))\n\n"
        "def clear_project_import_cache():\n"
        "    cached = [name for name in sys.modules if name == \"lst_models\" or name.startswith(\"lst_models.\")]\n"
        "    for name in cached:\n"
        "        del sys.modules[name]\n"
        "    importlib.invalidate_caches()\n\n"
        "clear_project_import_cache()\n\n"
        "print(\"PROJECT_ROOT:\", PROJECT_ROOT)\n"
        "print(\"PROJECT_BOOTSTRAP_MODE:\", PROJECT_BOOTSTRAP_MODE)\n"
        "print(\"PROJECT_COMMIT:\", PROJECT_REPO_COMMIT)\n"
        "print(\"STAGE00_RUN_ID:\", STAGE00_RUN_ID)\n"
        "print(\"STAGE01_RUN_ID:\", STAGE01_RUN_ID)\n"
        "print(\"STAGE02_RUN_ID:\", STAGE02_RUN_ID)\n"
        "print(\"SUPERSEDED_STAGE02_RUN_IDS:\", SUPERSEDED_STAGE02_RUN_IDS)\n"
        "print(\"FROZEN_SEEDS:\", FROZEN_SEEDS)\n"
        "print(\"OUTPUT_DIR:\", OUTPUT_DIR)\n"
        "print(\"CHECKPOINT_ROOT:\", CHECKPOINT_ROOT)\n"
        "print(\"RUN_STAGE03:\", RUN_STAGE03)\n"
        "print(\"RUN_STAGE03_CHECKPOINT_MIRROR:\", RUN_STAGE03_CHECKPOINT_MIRROR)\n"
        "print(\"RUN_STAGE03_DRIVE_BACKUP:\", RUN_STAGE03_DRIVE_BACKUP)\n",
    ),
    (
        "markdown",
        "## Config Load, Runtime Injection, And Contract Check\n\n"
        "This cell loads the Stage 03 config sidecar, injects the notebook "
        "runtime paths and exact upstream run ids BEFORE the contract asserts "
        "(runtime paths are part of the executable contract), and checks the "
        "frozen blocks. It does not refit or score anything.\n",
    ),
    (
        "code",
        "try:\n"
        "    import yaml\n"
        "except ModuleNotFoundError as exc:\n"
        "    raise ModuleNotFoundError(\"PyYAML is required to read the Stage 03 config.\") from exc\n\n"
        "def require_path(path):\n"
        "    if not path.exists():\n"
        "        raise FileNotFoundError(f\"missing required Stage 03 file: {path}\")\n\n"
        "require_path(STAGE_CONFIG_PATH)\n"
        "require_path(PROTOCOL_PATH)\n"
        "require_path(RAW_DATA_MANIFEST_PATH)\n\n"
        "with STAGE_CONFIG_PATH.open(\"r\", encoding=\"utf-8\") as handle:\n"
        "    stage03_config = yaml.safe_load(handle)\n\n"
        "stage_inputs = stage03_config[\"inputs\"]\n"
        "stage_outputs = stage03_config[\"outputs\"]\n"
        "stage_checkpointing = stage03_config[\"checkpointing\"]\n"
        "stage_inputs[\"stage00_run_id\"] = STAGE00_RUN_ID\n"
        "stage_inputs[\"stage00_runtime_run_dir\"] = str(STAGE00_OUTPUT_DIR)\n"
        "stage_inputs[\"stage00_drive_path_parts\"] = STAGE00_DRIVE_PATH_PARTS\n"
        "stage_inputs[\"stage01_run_id\"] = STAGE01_RUN_ID\n"
        "stage_inputs[\"stage01_runtime_run_dir\"] = str(STAGE01_OUTPUT_DIR)\n"
        "stage_inputs[\"stage01_drive_path_parts\"] = STAGE01_DRIVE_PATH_PARTS\n"
        "stage_inputs[\"stage02_run_id\"] = STAGE02_RUN_ID\n"
        "stage_inputs[\"stage02_runtime_run_dir\"] = str(STAGE02_OUTPUT_DIR)\n"
        "stage_inputs[\"stage02_drive_path_parts\"] = STAGE02_DRIVE_PATH_PARTS\n"
        "stage_inputs[\"superseded_stage02_run_ids\"] = SUPERSEDED_STAGE02_RUN_IDS\n"
        "stage_inputs[\"raw_data_dir\"] = str(RAW_DATA_DIR)\n"
        "stage_outputs[\"output_dir\"] = str(OUTPUT_DIR)\n"
        "stage_checkpointing[\"checkpoint_dir\"] = str(CHECKPOINT_ROOT)\n"
        "if RESUME_STAGE03_RUN_ID:\n"
        "    resume_checkpoint_dir = RESUME_STAGE03_CHECKPOINT_DIR or str(CHECKPOINT_ROOT / RESUME_STAGE03_RUN_ID)\n"
        "    stage03_config[\"resume\"] = {\n"
        "        \"enabled\": True,\n"
        "        \"run_id\": RESUME_STAGE03_RUN_ID,\n"
        "        \"checkpoint_dir\": resume_checkpoint_dir,\n"
        "    }\n"
        "    print(\"RESUME MODE: continuing run\", RESUME_STAGE03_RUN_ID, \"from\", resume_checkpoint_dir)\n\n"
        "assert stage03_config[\"stage_name\"] == STAGE_NAME\n"
        "assert stage03_config[\"route\"] == ROUTE\n"
        "assert stage03_config[\"scope\"] == SCOPE\n"
        "assert stage03_config[\"holdout_test_contact\"] is HOLDOUT_TEST_CONTACT\n"
        "assert stage03_config[\"official_validation_contact\"] is OFFICIAL_VALIDATION_CONTACT\n"
        "assert stage03_config[\"official_validation_for_selection\"] is OFFICIAL_VALIDATION_FOR_SELECTION\n"
        "assert stage_inputs[\"stage00_run_id\"] == STAGE00_RUN_ID\n"
        "assert Path(stage_inputs[\"stage00_runtime_run_dir\"]) == STAGE00_OUTPUT_DIR\n"
        "assert stage_inputs[\"stage01_run_id\"] == STAGE01_RUN_ID\n"
        "assert Path(stage_inputs[\"stage01_runtime_run_dir\"]) == STAGE01_OUTPUT_DIR\n"
        "assert stage_inputs[\"stage02_run_id\"] == STAGE02_RUN_ID\n"
        "assert Path(stage_inputs[\"stage02_runtime_run_dir\"]) == STAGE02_OUTPUT_DIR\n"
        "assert stage_inputs[\"stage02_run_id\"] not in stage_inputs[\"superseded_stage02_run_ids\"]\n"
        "assert Path(stage_inputs[\"raw_data_dir\"]) == RAW_DATA_DIR\n"
        "assert Path(stage_outputs[\"output_dir\"]) == OUTPUT_DIR\n"
        "assert Path(stage_checkpointing[\"checkpoint_dir\"]) == CHECKPOINT_ROOT\n"
        "assert stage_inputs[\"raw_data_manifest\"] == \"configs/lst_models_data.yaml\"\n"
        "assert stage03_config[\"readout\"][\"seeds\"] == FROZEN_SEEDS\n"
        "assert stage03_config[\"readout\"][\"score_each_seed_candidate_exactly_once\"] is True\n"
        "assert stage03_config[\"readout\"][\"refit_rows\"] == \"all_eligible_official_train_rows\"\n"
        "assert stage03_config[\"readout\"][\"scoring_rows\"] == \"all_eligible_official_validation_rows\"\n"
        "assert int(stage03_config[\"readout\"][\"max_materialized_train_bytes\"]) > 0\n"
        "criteria = stage03_config[\"predeclared_criteria\"]\n"
        "assert criteria[\"aggregate\"] == \"mean_over_seeds\"\n"
        "assert criteria[\"minimum_positive_ticker_count\"] == 3\n"
        "assert criteria[\"require_delta_macro_f1_vs_stratified_dummy_train_prior_positive\"] is True\n"
        "assert criteria[\"require_delta_macro_f1_vs_majority_train_prior_positive\"] is True\n"
        "fallback_policy = stage03_config[\"fallback_policy\"]\n"
        "assert fallback_policy[\"after_first_scoring_event\"] == \"never_activate\"\n"
        "assert \"weak_validation_metrics\" in fallback_policy[\"forbidden_triggers\"]\n"
        "assert stage03_config[\"baseline_controls\"][\"mandatory\"] == [\"stratified_dummy_train_prior\", \"majority_train_prior\", \"constant_up\", \"constant_down\"]\n"
        "assert stage03_config[\"lightgbm_training_defaults\"][\"early_stopping_validation_source\"] == \"inner_train_chronological_tail\"\n"
        "assert int(stage03_config[\"lightgbm_training_defaults\"][\"early_stopping_rounds\"]) == 25\n"
        "torch_defaults = stage03_config[\"probe_training_defaults\"][\"torch\"]\n"
        "assert torch_defaults[\"early_stopping\"] == \"inner_train_chronological_tail\"\n"
        "assert int(torch_defaults[\"early_stopping_patience\"]) == 8\n"
        "assert int(torch_defaults[\"epochs\"]) == 64\n"
        "assert stage03_config[\"forbidden\"][\"wording\"], \"forbidden wording list must be present\"\n"
        "expected_output_names = {\n"
        "    \"validation_readout\": \"03_validation_readout.csv\",\n"
        "    \"per_ticker_readout\": \"03_per_ticker_readout.csv\",\n"
        "    \"seed_summary\": \"03_seed_summary.csv\",\n"
        "    \"same_row_baselines\": \"03_same_row_baselines.csv\",\n"
        "    \"validation_predictions\": \"03_validation_predictions.csv\",\n"
        "    \"decision_record\": \"03_decision_record.json\",\n"
        "    \"manifest\": \"run_manifest.json\",\n"
        "    \"artifact_inventory\": \"artifact_inventory.csv\",\n"
        "}\n"
        "for output_key, output_name in expected_output_names.items():\n"
        "    assert stage_outputs[output_key] == output_name\n\n"
        "print(json.dumps({\n"
        "    \"stage_name\": stage03_config[\"stage_name\"],\n"
        "    \"source_stage00_run_id\": stage_inputs[\"stage00_run_id\"],\n"
        "    \"source_stage01_run_id\": stage_inputs[\"stage01_run_id\"],\n"
        "    \"source_stage02_run_id\": stage_inputs[\"stage02_run_id\"],\n"
        "    \"superseded_stage02_run_ids\": stage_inputs[\"superseded_stage02_run_ids\"],\n"
        "    \"frozen_seeds\": stage03_config[\"readout\"][\"seeds\"],\n"
        "    \"max_materialized_train_bytes\": stage03_config[\"readout\"][\"max_materialized_train_bytes\"],\n"
        "    \"official_validation_contact\": stage03_config[\"official_validation_contact\"],\n"
        "    \"official_validation_for_selection\": stage03_config[\"official_validation_for_selection\"],\n"
        "    \"holdout_test_contact\": stage03_config[\"holdout_test_contact\"],\n"
        "}, indent=2))\n",
    ),
    (
        "markdown",
        "## Upstream Inputs: Stage 00, Stage 01, Stage 02, And Raw Data\n\n"
        "Stage 03 verifies the full frozen chain before any refit. If the "
        "Colab runtime was restarted, this cell downloads the three exact "
        "upstream run folders by Drive path parts (duplicate Drive matches "
        "are a hard error) and the raw ticker files by Drive file ID.\n",
    ),
    (
        "code",
        "from lst_models.artifacts import require_artifacts\n\n"
        "def get_drive_service():\n"
        "    try:\n"
        "        from google.colab import auth\n"
        "        from googleapiclient.discovery import build\n"
        "    except ImportError as exc:\n"
        "        raise RuntimeError(\"Drive access only works inside Colab with Google API dependencies.\") from exc\n"
        "    auth.authenticate_user()\n"
        "    return build(\"drive\", \"v3\")\n\n"
        "def find_unique_drive_child(service, parent_id, name, mime_type=None):\n"
        "    escaped_name = quote_drive_query_value(name)\n"
        "    query_parts = [f\"name = '{escaped_name}'\", f\"'{parent_id}' in parents\", \"trashed = false\"]\n"
        "    if mime_type:\n"
        "        query_parts.append(f\"mimeType = '{mime_type}'\")\n"
        "    response = service.files().list(q=\" and \".join(query_parts), spaces=\"drive\", fields=\"files(id, name, mimeType, size)\", pageSize=10).execute()\n"
        "    matches = response.get(\"files\", [])\n"
        "    if len(matches) != 1:\n"
        "        raise FileNotFoundError(f\"expected exactly one Drive item named {name!r} under parent {parent_id}; found {len(matches)}\")\n"
        "    return matches[0]\n\n"
        "def resolve_drive_folder(service, path_parts):\n"
        "    folder_id = \"root\"\n"
        "    folder_mime = \"application/vnd.google-apps.folder\"\n"
        "    for folder_name in path_parts:\n"
        "        folder = find_unique_drive_child(service, folder_id, folder_name, folder_mime)\n"
        "        folder_id = folder[\"id\"]\n"
        "    return folder_id\n\n"
        "def download_drive_file(service, file_id, output_path):\n"
        "    from googleapiclient.http import MediaIoBaseDownload\n"
        "    output_path.parent.mkdir(parents=True, exist_ok=True)\n"
        "    request = service.files().get_media(fileId=file_id)\n"
        "    with output_path.open(\"wb\") as handle:\n"
        "        downloader = MediaIoBaseDownload(handle, request)\n"
        "        done = False\n"
        "        while not done:\n"
        "            _, done = downloader.next_chunk()\n\n"
        "def ensure_drive_folder(service, parent_id, name):\n"
        "    folder_mime = \"application/vnd.google-apps.folder\"\n"
        "    escaped_name = quote_drive_query_value(name)\n"
        "    query = f\"name = '{escaped_name}' and '{parent_id}' in parents and trashed = false and mimeType = '{folder_mime}'\"\n"
        "    matches = service.files().list(q=query, fields=\"files(id, name, webViewLink)\", pageSize=10).execute().get(\"files\", [])\n"
        "    if len(matches) == 1:\n"
        "        return matches[0][\"id\"]\n"
        "    if len(matches) > 1:\n"
        "        raise RuntimeError(f\"Duplicate Drive folders named {name!r} under parent {parent_id}\")\n"
        "    created = service.files().create(body={\"name\": name, \"mimeType\": folder_mime, \"parents\": [parent_id]}, fields=\"id, name, webViewLink\").execute()\n"
        "    return created[\"id\"]\n\n"
        "def ensure_drive_path(service, path_parts):\n"
        "    folder_id = \"root\"\n"
        "    for part in path_parts:\n"
        "        folder_id = ensure_drive_folder(service, folder_id, part)\n"
        "    return folder_id\n\n"
        "def find_drive_children(service, parent_id, name):\n"
        "    escaped_name = quote_drive_query_value(name)\n"
        "    query = f\"name = '{escaped_name}' and '{parent_id}' in parents and trashed = false\"\n"
        "    return service.files().list(q=query, fields=\"files(id, name, mimeType, size, webViewLink)\", pageSize=10).execute().get(\"files\", [])\n\n"
        "def upload_or_update_drive_file(service, parent_id, local_path, display_name=None):\n"
        "    from googleapiclient.http import MediaFileUpload\n"
        "    name = display_name or local_path.name\n"
        "    matches = find_drive_children(service, parent_id, name)\n"
        "    media = MediaFileUpload(str(local_path), resumable=True)\n"
        "    if len(matches) == 0:\n"
        "        uploaded = service.files().create(body={\"name\": name, \"parents\": [parent_id]}, media_body=media, fields=\"id, name, size, webViewLink\").execute()\n"
        "        action = \"uploaded\"\n"
        "    elif len(matches) == 1:\n"
        "        uploaded = service.files().update(fileId=matches[0][\"id\"], media_body=media, fields=\"id, name, size, webViewLink\").execute()\n"
        "        action = \"updated\"\n"
        "    else:\n"
        "        raise RuntimeError(f\"Duplicate Drive files named {name!r} under parent {parent_id}\")\n"
        "    print(f\"{action}: {name}\")\n"
        "    return dict(uploaded)\n\n"
        "def sync_stage_artifacts_from_drive(service, output_dir, path_parts, required_names, label):\n"
        "    run_folder_id = resolve_drive_folder(service, path_parts)\n"
        "    for artifact_name in required_names:\n"
        "        output_path = Path(output_dir) / artifact_name\n"
        "        if output_path.exists():\n"
        "            continue\n"
        "        file_meta = find_unique_drive_child(service, run_folder_id, artifact_name)\n"
        "        download_drive_file(service, file_meta[\"id\"], output_path)\n"
        "        print(f\"downloaded {label}: {artifact_name}\")\n\n"
        "def sync_raw_data_from_drive(service):\n"
        "    with RAW_DATA_MANIFEST_PATH.open(\"r\", encoding=\"utf-8\") as handle:\n"
        "        raw_manifest = yaml.safe_load(handle)\n"
        "    raw_source = raw_manifest[\"raw_source\"]\n"
        "    RAW_DATA_DIR.mkdir(parents=True, exist_ok=True)\n"
        "    for ticker in raw_manifest[\"tickers\"]:\n"
        "        spec = raw_source[\"files\"][ticker]\n"
        "        output_path = RAW_DATA_DIR / spec[\"name\"]\n"
        "        if output_path.exists():\n"
        "            continue\n"
        "        download_drive_file(service, spec[\"file_id\"], output_path)\n"
        "        print(f\"downloaded raw data: {output_path.name}\")\n\n"
        "required_stage00_artifacts = stage_inputs[\"required_stage00_artifacts\"]\n"
        "required_stage01_artifacts = stage_inputs[\"required_stage01_artifacts\"]\n"
        "required_stage02_artifacts = stage_inputs[\"required_stage02_artifacts\"]\n"
        "if RUN_STAGE03:\n"
        "    service = get_drive_service()\n"
        "    with RAW_DATA_MANIFEST_PATH.open(\"r\", encoding=\"utf-8\") as handle:\n"
        "        raw_manifest = yaml.safe_load(handle)\n"
        "    missing_raw = [raw_manifest[\"raw_source\"][\"files\"][ticker][\"name\"] for ticker in raw_manifest[\"tickers\"] if not (RAW_DATA_DIR / raw_manifest[\"raw_source\"][\"files\"][ticker][\"name\"]).exists()]\n"
        "    if missing_raw and RUN_RAW_DATA_SYNC:\n"
        "        print(\"Missing raw data files; syncing from Drive file IDs:\", missing_raw)\n"
        "        sync_raw_data_from_drive(service)\n"
        "    stage00_missing = [name for name in required_stage00_artifacts if not (STAGE00_OUTPUT_DIR / name).exists()]\n"
        "    if stage00_missing and RUN_STAGE00_DRIVE_SYNC:\n"
        "        sync_stage_artifacts_from_drive(service, STAGE00_OUTPUT_DIR, STAGE00_DRIVE_PATH_PARTS, stage00_missing, \"stage00\")\n"
        "    stage01_missing = [name for name in required_stage01_artifacts if not (STAGE01_OUTPUT_DIR / name).exists()]\n"
        "    if stage01_missing and RUN_STAGE01_DRIVE_SYNC:\n"
        "        sync_stage_artifacts_from_drive(service, STAGE01_OUTPUT_DIR, STAGE01_DRIVE_PATH_PARTS, stage01_missing, \"stage01\")\n"
        "    stage02_missing = [name for name in required_stage02_artifacts if not (STAGE02_OUTPUT_DIR / name).exists()]\n"
        "    if stage02_missing and RUN_STAGE02_DRIVE_SYNC:\n"
        "        sync_stage_artifacts_from_drive(service, STAGE02_OUTPUT_DIR, STAGE02_DRIVE_PATH_PARTS, stage02_missing, \"stage02\")\n"
        "    require_artifacts(STAGE00_OUTPUT_DIR, required_stage00_artifacts)\n"
        "    require_artifacts(STAGE01_OUTPUT_DIR, required_stage01_artifacts)\n"
        "    require_artifacts(STAGE02_OUTPUT_DIR, required_stage02_artifacts)\n"
        "    print(\"Stage 00, Stage 01, Stage 02, and raw data input checks passed.\")\n"
        "else:\n"
        "    print(\"RUN_STAGE03=False; upstream input sync skipped.\")\n",
    ),
    (
        "markdown",
        "## Pre-Flight Feasibility Estimate (Before Any Scoring)\n\n"
        "Protocol section 5 feasibility clause: estimate the materialized "
        "float32 tensor bytes for refit (train) plus scored validation rows "
        "from `sample_event_index.csv` row counts and abort BEFORE any "
        "scoring event if the primary candidate's combined estimate exceeds "
        "`readout.max_materialized_train_bytes`. The sample policy is never "
        "tuned after a scoring event.\n",
    ),
    (
        "code",
        "if RUN_STAGE03:\n"
        "    import pandas as pd\n\n"
        "    handoff_path = STAGE02_OUTPUT_DIR / \"02_stage03_handoff.json\"\n"
        "    candidate_inputs_path = STAGE01_OUTPUT_DIR / \"01_candidate_inputs.json\"\n"
        "    sample_event_index_path = STAGE00_OUTPUT_DIR / \"sample_event_index.csv\"\n"
        "    for path in [handoff_path, candidate_inputs_path, sample_event_index_path]:\n"
        "        require_path(path)\n"
        "    stage02_handoff = json.loads(handoff_path.read_text(encoding=\"utf-8\"))\n"
        "    if stage02_handoff.get(\"ready_for_stage03\") is not True:\n"
        "        print(\"Stage 02 handoff records ready_for_stage03=false; the runner will write a blocked decision record with zero scoring events.\")\n"
        "    else:\n"
        "        candidate_inputs = json.loads(candidate_inputs_path.read_text(encoding=\"utf-8\"))[\"candidate_inputs\"]\n"
        "        events = pd.read_csv(sample_event_index_path)\n"
        "        valid_label = events[\"valid_label\"].map(lambda value: str(value).strip().lower() in {\"true\", \"1\", \"yes\"})\n"
        "        n_train_rows = int(((events[\"split\"] == \"train\") & valid_label).sum())\n"
        "        n_validation_rows = int(((events[\"split\"] == \"validation\") & valid_label).sum())\n\n"
        "        def estimate_candidate_bytes(candidate):\n"
        "            candidate_id = str(candidate[\"candidate_id\"])\n"
        "            matches = [entry for entry in candidate_inputs if str(entry[\"candidate_id\"]) == candidate_id]\n"
        "            if len(matches) != 1:\n"
        "                raise ValueError(f\"expected exactly one 01_candidate_inputs.json entry for {candidate_id!r}; found {len(matches)}\")\n"
        "            window_size = int(candidate[\"window_size\"])\n"
        "            n_features = len(matches[0][\"feature_columns\"])\n"
        "            per_row_bytes = window_size * n_features * 4\n"
        "            return {\n"
        "                \"candidate_id\": candidate_id,\n"
        "                \"window_size\": window_size,\n"
        "                \"n_features\": n_features,\n"
        "                \"train_bytes\": n_train_rows * per_row_bytes,\n"
        "                \"validation_bytes\": n_validation_rows * per_row_bytes,\n"
        "                \"combined_bytes\": (n_train_rows + n_validation_rows) * per_row_bytes,\n"
        "            }\n\n"
        "        primary_estimate = estimate_candidate_bytes(stage02_handoff[\"primary_candidate\"])\n"
        "        fallback_estimate = estimate_candidate_bytes(stage02_handoff[\"fallback_candidate\"])\n"
        "        max_bytes = int(stage03_config[\"readout\"][\"max_materialized_train_bytes\"])\n"
        "        print(json.dumps({\n"
        "            \"n_train_rows_upper_bound\": n_train_rows,\n"
        "            \"n_validation_rows_upper_bound\": n_validation_rows,\n"
        "            \"primary_estimate\": primary_estimate,\n"
        "            \"fallback_estimate_context_only\": fallback_estimate,\n"
        "            \"max_materialized_train_bytes\": max_bytes,\n"
        "        }, indent=2))\n"
        "        if primary_estimate[\"combined_bytes\"] > max_bytes:\n"
        "            raise RuntimeError(\n"
        "                \"Stage 03 pre-flight infeasible BEFORE any scoring event: \"\n"
        "                f\"primary combined estimate {primary_estimate['combined_bytes']} bytes exceeds \"\n"
        "                f\"max_materialized_train_bytes {max_bytes}; amend the config to the predeclared \"\n"
        "                \"deterministic_even_stride_by_ticker_label fallback policy and start a fresh run \"\n"
        "                \"(protocol section 5); zero scoring events have occurred\"\n"
        "            )\n"
        "        print(\"Pre-flight feasibility passed; proceeding is authorized.\")\n"
        "else:\n"
        "    print(\"RUN_STAGE03=False; pre-flight feasibility estimate skipped.\")\n",
    ),
    (
        "markdown",
        "## Checkpoint Mirror To Drive\n\n"
        "The runner writes per-seed recovery checkpoints (partial output rows "
        "plus `checkpoint_manifest.json`) under the local checkpoint root. "
        "This cell defines a background mirror that uploads mtime-stable "
        "checkpoint files to "
        "`My Drive/lst_models/checkpoints/03_frozen_validation_readout/<run_id>/` "
        "during the run, so a lost runtime keeps its recovery state. "
        "Checkpoints are recovery state only, never evidence artifacts.\n",
    ),
    (
        "code",
        "STAGE03_MIRROR_STATE = {\"stop\": False, \"errors\": [], \"uploaded_mtimes\": {}, \"folder_ids\": {}}\n"
        "STAGE03_MIRROR_POLL_SECONDS = 120\n"
        "STAGE03_MIRROR_STABLE_SECONDS = 10\n\n"
        "def mirror_stage03_checkpoints_once(service):\n"
        "    if not CHECKPOINT_ROOT.exists():\n"
        "        return 0\n"
        "    uploaded_count = 0\n"
        "    now = time.time()\n"
        "    for path in sorted(CHECKPOINT_ROOT.rglob(\"*\")):\n"
        "        if not path.is_file():\n"
        "            continue\n"
        "        mtime = path.stat().st_mtime\n"
        "        if now - mtime < STAGE03_MIRROR_STABLE_SECONDS:\n"
        "            continue\n"
        "        key = str(path)\n"
        "        if STAGE03_MIRROR_STATE[\"uploaded_mtimes\"].get(key) == mtime:\n"
        "            continue\n"
        "        relative = path.relative_to(CHECKPOINT_ROOT)\n"
        "        parent_parts = tuple(CHECKPOINT_DRIVE_BASE_PARTS + list(relative.parent.parts)) if relative.parent != Path(\".\") else tuple(CHECKPOINT_DRIVE_BASE_PARTS)\n"
        "        folder_id = STAGE03_MIRROR_STATE[\"folder_ids\"].get(parent_parts)\n"
        "        if folder_id is None:\n"
        "            folder_id = ensure_drive_path(service, list(parent_parts))\n"
        "            STAGE03_MIRROR_STATE[\"folder_ids\"][parent_parts] = folder_id\n"
        "        upload_or_update_drive_file(service, folder_id, path)\n"
        "        STAGE03_MIRROR_STATE[\"uploaded_mtimes\"][key] = mtime\n"
        "        uploaded_count += 1\n"
        "    return uploaded_count\n\n"
        "def stage03_checkpoint_mirror_loop():\n"
        "    try:\n"
        "        mirror_service = get_drive_service()\n"
        "    except Exception as exc:\n"
        "        STAGE03_MIRROR_STATE[\"errors\"].append(f\"mirror auth failed: {type(exc).__name__}: {exc}\")\n"
        "        print(\"checkpoint mirror disabled:\", STAGE03_MIRROR_STATE[\"errors\"][-1])\n"
        "        return\n"
        "    while not STAGE03_MIRROR_STATE[\"stop\"]:\n"
        "        try:\n"
        "            mirror_stage03_checkpoints_once(mirror_service)\n"
        "        except Exception as exc:\n"
        "            STAGE03_MIRROR_STATE[\"errors\"].append(f\"{type(exc).__name__}: {exc}\")\n"
        "            print(\"checkpoint mirror error (recorded, run continues):\", STAGE03_MIRROR_STATE[\"errors\"][-1])\n"
        "        for _ in range(STAGE03_MIRROR_POLL_SECONDS):\n"
        "            if STAGE03_MIRROR_STATE[\"stop\"]:\n"
        "                break\n"
        "            time.sleep(1)\n\n"
        "def start_stage03_checkpoint_mirror():\n"
        "    STAGE03_MIRROR_STATE[\"stop\"] = False\n"
        "    thread = threading.Thread(target=stage03_checkpoint_mirror_loop, name=\"stage03_checkpoint_mirror\", daemon=True)\n"
        "    thread.start()\n"
        "    return thread\n\n"
        "RESUME_REQUIRED_CHECKPOINT_FILES = [\n"
        "    \"checkpoint_manifest.json\",\n"
        "    \"03_ledger_state_partial.json\",\n"
        "    \"03_validation_readout_partial.csv\",\n"
        "    \"03_same_row_baselines_partial.csv\",\n"
        "    \"03_validation_predictions_partial.csv\",\n"
        "]\n\n"
        "def fetch_resume_checkpoint_from_drive():\n"
        "    \"\"\"Restore the exact checkpoint folder for RESUME_STAGE03_RUN_ID from\n"
        "    Drive when the local runtime lost it (exact path parts, no scans).\"\"\"\n"
        "    local_dir = Path(RESUME_STAGE03_CHECKPOINT_DIR or str(CHECKPOINT_ROOT / RESUME_STAGE03_RUN_ID))\n"
        "    missing = [name for name in RESUME_REQUIRED_CHECKPOINT_FILES if not (local_dir / name).exists()]\n"
        "    if not missing:\n"
        "        print(\"resume checkpoint complete locally:\", local_dir)\n"
        "        return\n"
        "    service = get_drive_service()\n"
        "    drive_parts = CHECKPOINT_DRIVE_BASE_PARTS + [RESUME_STAGE03_RUN_ID]\n"
        "    sync_stage_artifacts_from_drive(service, local_dir, drive_parts, missing, \"stage03 resume checkpoint\")\n"
        "    still_missing = [name for name in RESUME_REQUIRED_CHECKPOINT_FILES if not (local_dir / name).exists()]\n"
        "    if still_missing:\n"
        "        raise FileNotFoundError(f\"resume checkpoint files missing after Drive fetch: {still_missing}\")\n\n"
        "if RUN_STAGE03 and RESUME_STAGE03_RUN_ID:\n"
        "    fetch_resume_checkpoint_from_drive()\n\n"
        "def stop_stage03_checkpoint_mirror(thread):\n"
        "    STAGE03_MIRROR_STATE[\"stop\"] = True\n"
        "    if thread is not None:\n"
        "        thread.join(timeout=STAGE03_MIRROR_POLL_SECONDS + 30)\n"
        "    final_service = get_drive_service()\n"
        "    STAGE03_MIRROR_STATE[\"uploaded_mtimes\"] = {}\n"
        "    uploaded = mirror_stage03_checkpoints_once(final_service)\n"
        "    print(f\"final checkpoint sweep uploaded {uploaded} files; recorded mirror errors: {len(STAGE03_MIRROR_STATE['errors'])}\")\n"
        "    if STAGE03_MIRROR_STATE[\"errors\"]:\n"
        "        print(json.dumps(STAGE03_MIRROR_STATE[\"errors\"], indent=2))\n\n"
        "print(\"Checkpoint mirror helpers ready; RUN_STAGE03_CHECKPOINT_MIRROR =\", RUN_STAGE03_CHECKPOINT_MIRROR)\n",
    ),
    (
        "markdown",
        "## Run Stage 03 (One-Shot Readout)\n\n"
        "The package-backed entry point is "
        "`lst_models.stages.frozen_validation_readout.run_stage`. Each frozen "
        "seed x candidate contacts official-validation rows exactly once; "
        "every scoring event lands in the decision-record ledger. The "
        "committed notebook remains inert by default. Do not re-run this "
        "cell after a successful scoring run; a crashed run is completed "
        "via the exact-run-id resume path, never by a fresh full rerun.\n",
    ),
    (
        "code",
        "if RUN_STAGE03:\n"
        "    try:\n"
        "        from lst_models.stages.frozen_validation_readout import run_stage\n"
        "    except ModuleNotFoundError as exc:\n"
        "        raise ModuleNotFoundError(\"Missing Stage 03 package entry point: src/lst_models/stages/frozen_validation_readout.py.\") from exc\n"
        "    mirror_thread = start_stage03_checkpoint_mirror() if RUN_STAGE03_CHECKPOINT_MIRROR else None\n"
        "    try:\n"
        "        result = run_stage(stage03_config)\n"
        "    finally:\n"
        "        if RUN_STAGE03_CHECKPOINT_MIRROR:\n"
        "            stop_stage03_checkpoint_mirror(mirror_thread)\n"
        "    display(result)\n"
        "    STAGE03_RUN_ID = Path(result.output_dir).name\n"
        "    if Path(result.output_dir).parent != OUTPUT_DIR:\n"
        "        raise RuntimeError(f\"Stage 03 output dir mismatch: {Path(result.output_dir).parent} != {OUTPUT_DIR}\")\n"
        "    print(\"STAGE03_RUN_ID:\", STAGE03_RUN_ID)\n"
        "else:\n"
        "    print(\"RUN_STAGE03=False; Stage 03 one-shot readout not executed.\")\n",
    ),
    (
        "markdown",
        "## Durable Drive Result Save\n\n"
        "Immediately after `run_stage` returns, this cell validates the "
        "required Stage 03 outputs, refuses upload unless the run manifest "
        "records `official_validation_for_selection=false`, "
        "`holdout_test_contact=false`, and `no_final_model_selected=true`, "
        "and uploads the run folder to "
        "`My Drive/lst_models/results/03_frozen_validation_readout/<run_id>/`. "
        "`drive_backup_manifest.json` is written and uploaded last; its own "
        "entry records size null (self-reference).\n",
    ),
    (
        "code",
        "def backup_stage03_results_to_drive(output_run_dir):\n"
        "    run_dir = Path(output_run_dir)\n"
        "    if not run_dir.exists():\n"
        "        raise FileNotFoundError(f\"Stage 03 output folder not found: {run_dir}\")\n"
        "    run_id = run_dir.name\n"
        "    missing = [name for name in REQUIRED_STAGE03_OUTPUTS if not (run_dir / name).exists()]\n"
        "    blocked_run = False\n"
        "    if missing:\n"
        "        decision_record_path = run_dir / \"03_decision_record.json\"\n"
        "        manifest_probe_path = run_dir / \"run_manifest.json\"\n"
        "        if decision_record_path.exists() and manifest_probe_path.exists():\n"
        "            probe_record = json.loads(decision_record_path.read_text(encoding=\"utf-8\"))\n"
        "            if str(probe_record.get(\"decision\", \"\")).startswith(\"do_not_start_stage03\"):\n"
        "                blocked_run = True\n"
        "                missing = [name for name in [\"03_decision_record.json\", \"run_manifest.json\", \"artifact_inventory.csv\"] if not (run_dir / name).exists()]\n"
        "    if missing:\n"
        "        raise FileNotFoundError(\n"
        "            \"Missing required Stage 03 artifacts before Drive backup in \"\n"
        "            f\"{run_dir}: {missing}\"\n"
        "        )\n"
        "    run_manifest = json.loads((run_dir / \"run_manifest.json\").read_text(encoding=\"utf-8\"))\n"
        "    if run_manifest.get(\"official_validation_for_selection\") is not False:\n"
        "        raise ValueError(\"Stage 03 backup refused: run manifest must record official_validation_for_selection=false\")\n"
        "    if run_manifest.get(\"holdout_test_contact\") is not False:\n"
        "        raise ValueError(\"Stage 03 backup refused: run manifest must record holdout_test_contact=false\")\n"
        "    if run_manifest.get(\"no_final_model_selected\") is not True:\n"
        "        raise ValueError(\"Stage 03 backup refused: run manifest must record no_final_model_selected=true\")\n"
        "    if run_manifest.get(\"source_stage02_run_id\") != STAGE02_RUN_ID:\n"
        "        raise ValueError(f\"Stage 03 backup refused: manifest source_stage02_run_id != {STAGE02_RUN_ID}\")\n"
        "    decision_record = json.loads((run_dir / \"03_decision_record.json\").read_text(encoding=\"utf-8\"))\n"
        "    service = get_drive_service()\n"
        "    drive_path_parts = STAGE03_DRIVE_RESULT_PATH_PARTS + [run_id]\n"
        "    drive_folder_id = ensure_drive_path(service, drive_path_parts)\n"
        "    backup_manifest_path = run_dir / \"drive_backup_manifest.json\"\n"
        "    local_files = sorted(path for path in run_dir.rglob(\"*\") if path.is_file() and path.name != backup_manifest_path.name)\n"
        "    uploads = []\n"
        "    for path in local_files:\n"
        "        uploaded = upload_or_update_drive_file(service, drive_folder_id, path)\n"
        "        uploaded[\"bytes\"] = path.stat().st_size\n"
        "        uploads.append(uploaded)\n"
        "    backup_manifest = {\n"
        "        \"stage_name\": STAGE_NAME,\n"
        "        \"run_id\": run_id,\n"
        "        \"stage_run_id\": run_id,\n"
        "        \"blocked_run\": blocked_run,\n"
        "        \"decision\": decision_record.get(\"decision\"),\n"
        "        \"official_validation_scoring_events\": decision_record.get(\"official_validation_scoring_events\"),\n"
        "        \"readout_complete\": decision_record.get(\"readout_complete\"),\n"
        "        \"local_output_dir\": str(run_dir),\n"
        "        \"drive_path\": \"My Drive/\" + \"/\".join(drive_path_parts),\n"
        "        \"drive_path_parts\": drive_path_parts,\n"
        "        \"drive_folder_id\": drive_folder_id,\n"
        "        \"uploaded_file_names\": [upload[\"name\"] for upload in uploads],\n"
        "        \"uploaded_files\": uploads,\n"
        "        \"sync_timestamp_utc\": datetime.now(timezone.utc).isoformat(),\n"
        "        \"holdout_test_contact\": run_manifest.get(\"holdout_test_contact\"),\n"
        "        \"official_validation_for_selection\": run_manifest.get(\"official_validation_for_selection\"),\n"
        "        \"no_final_model_selected\": run_manifest.get(\"no_final_model_selected\"),\n"
        "    }\n"
        "    backup_manifest[\"uploaded_files\"] = backup_manifest[\"uploaded_files\"] + [\n"
        "        {\"name\": backup_manifest_path.name, \"bytes\": None, \"self_reference\": True}\n"
        "    ]\n"
        "    backup_manifest[\"uploaded_file_names\"].append(backup_manifest_path.name)\n"
        "    backup_manifest_path.write_text(json.dumps(backup_manifest, indent=2), encoding=\"utf-8\")\n"
        "    upload_or_update_drive_file(service, drive_folder_id, backup_manifest_path)\n"
        "    print(\"stage_run_id:\", backup_manifest[\"stage_run_id\"])\n"
        "    print(\"drive_path:\", backup_manifest[\"drive_path\"])\n"
        "    print(\"drive_folder_id:\", backup_manifest[\"drive_folder_id\"])\n"
        "    return backup_manifest\n\n"
        "if RUN_STAGE03_DRIVE_BACKUP and RUN_STAGE03:\n"
        "    if \"result\" not in globals():\n"
        "        raise RuntimeError(\"RUN_STAGE03_DRIVE_BACKUP=True requires running Stage 03 first.\")\n"
        "    stage03_drive_backup_manifest = backup_stage03_results_to_drive(result.output_dir)\n"
        "else:\n"
        "    print(\"RUN_STAGE03_DRIVE_BACKUP is disabled or RUN_STAGE03=False; no Stage 03 result backup uploaded.\")\n",
    ),
    (
        "markdown",
        "## Readout Display\n\n"
        "After an approved run, display only Stage 03 artifacts from "
        "`result.output_dir`. The display characterizes the frozen candidate "
        "against the predeclared criteria; it never ranks, selects, or "
        "tunes anything on official validation.\n",
    ),
    (
        "code",
        "if RUN_ARTIFACT_DISPLAY:\n"
        "    import pandas as pd\n\n"
        "    if \"result\" not in globals():\n"
        "        raise RuntimeError(\"RUN_ARTIFACT_DISPLAY=True requires running Stage 03 first.\")\n"
        "    run_dir = Path(result.output_dir)\n"
        "    decision_record_path = run_dir / \"03_decision_record.json\"\n"
        "    require_path(decision_record_path)\n"
        "    decision_record = json.loads(decision_record_path.read_text(encoding=\"utf-8\"))\n"
        "    print(json.dumps({\n"
        "        \"decision\": decision_record.get(\"decision\"),\n"
        "        \"criteria\": decision_record.get(\"criteria\"),\n"
        "        \"aggregate\": decision_record.get(\"aggregate\"),\n"
        "        \"official_validation_scoring_events\": decision_record.get(\"official_validation_scoring_events\"),\n"
        "        \"readout_complete\": decision_record.get(\"readout_complete\"),\n"
        "        \"fallback_activated\": decision_record.get(\"fallback_activated\"),\n"
        "        \"no_final_model_selected\": decision_record.get(\"no_final_model_selected\"),\n"
        "    }, indent=2))\n"
        "    for display_name in [\"03_seed_summary.csv\", \"03_validation_readout.csv\", \"03_same_row_baselines.csv\", \"03_per_ticker_readout.csv\"]:\n"
        "        display_path = run_dir / display_name\n"
        "        if display_path.exists():\n"
        "            display(pd.read_csv(display_path))\n"
        "        else:\n"
        "            print(f\"{display_name} not present (blocked or incomplete run).\")\n"
        "else:\n"
        "    print(\"RUN_ARTIFACT_DISPLAY=False; no Stage 03 artifacts displayed.\")\n",
    ),
    (
        "markdown",
        "## Honest Interpretation Template\n\n"
        "Allowed wording: `validation-only evidence`, `official validation "
        "readout`, `candidate met/did not meet predeclared "
        "validation-readout criteria`.\n\n"
        "Do not claim a final model, official validation winner, holdout "
        "winner, test winner, proved best model, proven generalization, "
        "profitability, holdout-readiness, selection by official validation, "
        "or a chosen threshold from this notebook. "
        "`no_final_model_selected=true` is retained in every Stage 03 "
        "output.\n\n"
        "Required context sentences for any summary based on this run:\n\n"
        "- Stage 02 absolute metrics and Stage 03 absolute metrics are not "
        "comparable: Stage 02 trials were fit and scored on stylized "
        "equal-allocation subsamples, while Stage 03 refits and scores on "
        "the natural row distribution (Zadrozny 2004). Only Stage 03 "
        "same-row deltas against the registry baselines support claims.\n"
        "- The refit mechanism reuses the frozen Stage 02 chronological-tail "
        "early stopping, so the scored model's weights never trained on the "
        "most recent tail of official-train rows; the tail only determined "
        "the stopping point.\n"
        "- The pinned R3 chain (Stage 00 `20260610_051705_347450`, Stage 01 "
        "`20260610_075002`) records full hash provenance; the superseded "
        "legacy chain predates the hash fields, and that legacy-provenance "
        "note applies only to superseded-chain history.\n"
        "- If a prior partial run was lost before its checkpoints reached "
        "Drive, disclose it here (date, candidate, seeds started) and carry "
        "the disclosure into Stage 05 validation-budget accounting.\n",
    ),
]


def build_notebook() -> nbf.NotebookNode:
    nb = nbf.v4.new_notebook()
    nb.metadata = {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "pygments_lexer": "ipython3"},
        "colab": {"provenance": []},
    }
    nb.cells = []
    for cell_type, cell_source in CELL_SPECS:
        if cell_type == "markdown":
            cell = nbf.v4.new_markdown_cell(cell_source)
        elif cell_type == "code":
            cell = nbf.v4.new_code_cell(cell_source)
            cell.outputs = []
            cell.execution_count = None
        else:
            raise ValueError(f"unsupported cell type: {cell_type}")
        cell.metadata = {}
        nb.cells.append(cell)
    return nb


def main() -> None:
    root = Path(__file__).resolve().parents[2]
    output_path = root / "notebooks" / "03_frozen_validation_readout_colab.ipynb"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(build_notebook(), output_path)
    print(output_path)


if __name__ == "__main__":
    main()
